// Generated by odin2 (version 0.3.19) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(model_trial_stochastic)]]
// [[dust2::time_type(discrete)]]
// [[dust2::parameter(n_vax, type = "int", rank = 0, required = FALSE, constant = TRUE)]]
// [[dust2::parameter(U0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(I0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(A0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(S0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(T0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(eta, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(sigma, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(psi, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(nu, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(mu, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(rho, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(lambda, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vea, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(ved, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(ves, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(w, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(D, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(diag_rec_a, type = "real_type", rank = 3, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(diag_rec_s, type = "real_type", rank = 3, required = TRUE, constant = FALSE)]]
class model_trial_stochastic {
public:
  model_trial_stochastic() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 16> state;
      } offset;
    } odin;
    struct dim_type {
      dust2::array::dimensions<2> U;
      dust2::array::dimensions<2> I;
      dust2::array::dimensions<2> A;
      dust2::array::dimensions<2> S;
      dust2::array::dimensions<2> T;
      dust2::array::dimensions<2> U0;
      dust2::array::dimensions<2> I0;
      dust2::array::dimensions<2> A0;
      dust2::array::dimensions<2> S0;
      dust2::array::dimensions<2> T0;
      dust2::array::dimensions<2> n_Uw;
      dust2::array::dimensions<2> n_Iw;
      dust2::array::dimensions<2> n_Aw;
      dust2::array::dimensions<2> n_Sw;
      dust2::array::dimensions<2> n_Tw;
      dust2::array::dimensions<2> N;
      dust2::array::dimensions<2> pye_trial;
      dust2::array::dimensions<2> pye_noscreen_trial;
      dust2::array::dimensions<2> n_UI;
      dust2::array::dimensions<2> n_IAS;
      dust2::array::dimensions<2> n_IA;
      dust2::array::dimensions<2> n_IS;
      dust2::array::dimensions<2> n_AUT;
      dust2::array::dimensions<2> n_AT;
      dust2::array::dimensions<2> n_AU;
      dust2::array::dimensions<2> n_ST;
      dust2::array::dimensions<2> n_TU;
      dust2::array::dimensions<2> screened;
      dust2::array::dimensions<2> p_U_ext;
      dust2::array::dimensions<2> p_I_ext;
      dust2::array::dimensions<2> p_S_ext;
      dust2::array::dimensions<2> p_A_ext;
      dust2::array::dimensions<2> p_T_ext;
      dust2::array::dimensions<2> n_U_ext;
      dust2::array::dimensions<2> n_I_ext;
      dust2::array::dimensions<2> n_S_ext;
      dust2::array::dimensions<2> n_A_ext;
      dust2::array::dimensions<2> n_T_ext;
      dust2::array::dimensions<2> Rel_U;
      dust2::array::dimensions<2> Rel_I;
      dust2::array::dimensions<2> Rel_A;
      dust2::array::dimensions<2> Rel_S;
      dust2::array::dimensions<2> Rel_T;
      dust2::array::dimensions<2> r_AT;
      dust2::array::dimensions<2> r_AU;
      dust2::array::dimensions<2> cum_incid;
      dust2::array::dimensions<2> cum_diag_a;
      dust2::array::dimensions<2> cum_diag_s;
      dust2::array::dimensions<2> cum_treated;
      dust2::array::dimensions<2> cum_screened;
      dust2::array::dimensions<2> cum_pye_trial_pov;
      dust2::array::dimensions<2> cum_pye_noscreen_trial_pov;
      dust2::array::dimensions<2> cum_pye_true;
      dust2::array::dimensions<3> n_diag_rec;
      dust2::array::dimensions<3> diag_rec_a;
      dust2::array::dimensions<3> diag_rec_s;
      dust2::array::dimensions<1> vea;
      dust2::array::dimensions<1> ved;
      dust2::array::dimensions<1> ves;
      dust2::array::dimensions<2> w;
      dust2::array::dimensions<1> D;
      dust2::array::dimensions<3> wU;
      dust2::array::dimensions<3> wI;
      dust2::array::dimensions<3> wA;
      dust2::array::dimensions<3> wS;
      dust2::array::dimensions<3> wT;
    } dim;
    real_type n_group;
    int n_vax;
    real_type eta;
    real_type sigma;
    real_type psi;
    real_type nu;
    real_type mu;
    real_type rho;
    real_type lambda;
    std::vector<real_type> r_AT;
    std::vector<real_type> U0;
    std::vector<real_type> I0;
    std::vector<real_type> A0;
    std::vector<real_type> S0;
    std::vector<real_type> T0;
    std::vector<real_type> vea;
    std::vector<real_type> ved;
    std::vector<real_type> ves;
    std::vector<real_type> w;
    std::vector<real_type> D;
    std::vector<real_type> diag_rec_a;
    std::vector<real_type> diag_rec_s;
    std::vector<real_type> r_AU;
    std::vector<real_type> Rel_U;
    std::vector<real_type> Rel_I;
    std::vector<real_type> Rel_S;
    std::vector<real_type> Rel_T;
    std::vector<real_type> Rel_A;
  };
  struct internal_state {
    std::vector<real_type> screened;
    std::vector<real_type> pye_trial;
    std::vector<real_type> pye_noscreen_trial;
    std::vector<real_type> p_U_ext;
    std::vector<real_type> p_I_ext;
    std::vector<real_type> p_S_ext;
    std::vector<real_type> p_T_ext;
    std::vector<real_type> p_A_ext;
    std::vector<real_type> n_U_ext;
    std::vector<real_type> n_I_ext;
    std::vector<real_type> n_S_ext;
    std::vector<real_type> n_T_ext;
    std::vector<real_type> n_A_ext;
    std::vector<real_type> n_UI;
    std::vector<real_type> n_IAS;
    std::vector<real_type> n_ST;
    std::vector<real_type> n_TU;
    std::vector<real_type> n_Uw;
    std::vector<real_type> n_Iw;
    std::vector<real_type> n_IA;
    std::vector<real_type> n_Sw;
    std::vector<real_type> n_AUT;
    std::vector<real_type> n_Tw;
    std::vector<real_type> n_IS;
    std::vector<real_type> n_Aw;
    std::vector<real_type> n_AT;
    std::vector<real_type> wU;
    std::vector<real_type> wI;
    std::vector<real_type> wS;
    std::vector<real_type> wT;
    std::vector<real_type> n_AU;
    std::vector<real_type> n_diag_rec;
    std::vector<real_type> wA;
  };
  using data_type = dust2::no_data;
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    shared_state::dim_type dim;
    const real_type n_group = 2;
    const int n_vax = dust2::r::read_int(parameters, "n_vax", 1);
    const real_type eta = dust2::r::read_real(parameters, "eta");
    const real_type sigma = dust2::r::read_real(parameters, "sigma");
    const real_type psi = dust2::r::read_real(parameters, "psi");
    const real_type nu = dust2::r::read_real(parameters, "nu");
    const real_type mu = dust2::r::read_real(parameters, "mu");
    const real_type rho = dust2::r::read_real(parameters, "rho");
    const real_type lambda = dust2::r::read_real(parameters, "lambda");
    dim.U.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.I.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.A.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.S.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.T.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.U0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.I0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.A0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.S0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.T0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_Uw.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_Iw.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_Aw.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_Sw.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_Tw.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.N.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.pye_trial.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.pye_noscreen_trial.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_UI.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_IAS.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_IA.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_IS.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_AUT.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_AT.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_AU.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_ST.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_TU.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.screened.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.p_U_ext.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.p_I_ext.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.p_S_ext.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.p_A_ext.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.p_T_ext.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_U_ext.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_I_ext.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_S_ext.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_A_ext.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_T_ext.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.Rel_U.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.Rel_I.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.Rel_A.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.Rel_S.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.Rel_T.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.r_AT.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.r_AU.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_incid.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_diag_a.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_diag_s.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_treated.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_screened.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_pye_trial_pov.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_pye_noscreen_trial_pov.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_pye_true.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_diag_rec.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.diag_rec_a.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.diag_rec_s.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.vea.set({static_cast<size_t>(n_vax)});
    dim.ved.set({static_cast<size_t>(n_vax)});
    dim.ves.set({static_cast<size_t>(n_vax)});
    dim.w.set({static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.D.set({static_cast<size_t>(n_vax)});
    dim.wU.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wI.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wA.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wS.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wT.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    std::vector<real_type> r_AT(dim.r_AT.size);
    for (size_t i = 1; i <= dim.r_AT.dim[0]; ++i) {
      for (size_t j = 1; j <= dim.r_AT.dim[1]; ++j) {
        r_AT[i - 1 + (j - 1) * dim.r_AT.mult[1]] = eta;
      }
    }
    std::vector<real_type> U0(dim.U0.size);
    dust2::r::read_real_array(parameters, dim.U0, U0.data(), "U0", true);
    std::vector<real_type> I0(dim.I0.size);
    dust2::r::read_real_array(parameters, dim.I0, I0.data(), "I0", true);
    std::vector<real_type> A0(dim.A0.size);
    dust2::r::read_real_array(parameters, dim.A0, A0.data(), "A0", true);
    std::vector<real_type> S0(dim.S0.size);
    dust2::r::read_real_array(parameters, dim.S0, S0.data(), "S0", true);
    std::vector<real_type> T0(dim.T0.size);
    dust2::r::read_real_array(parameters, dim.T0, T0.data(), "T0", true);
    std::vector<real_type> vea(dim.vea.size);
    dust2::r::read_real_array(parameters, dim.vea, vea.data(), "vea", true);
    std::vector<real_type> ved(dim.ved.size);
    dust2::r::read_real_array(parameters, dim.ved, ved.data(), "ved", true);
    std::vector<real_type> ves(dim.ves.size);
    dust2::r::read_real_array(parameters, dim.ves, ves.data(), "ves", true);
    std::vector<real_type> w(dim.w.size);
    dust2::r::read_real_array(parameters, dim.w, w.data(), "w", true);
    std::vector<real_type> D(dim.D.size);
    dust2::r::read_real_array(parameters, dim.D, D.data(), "D", true);
    std::vector<real_type> diag_rec_a(dim.diag_rec_a.size);
    dust2::r::read_real_array(parameters, dim.diag_rec_a, diag_rec_a.data(), "diag_rec_a", true);
    std::vector<real_type> diag_rec_s(dim.diag_rec_s.size);
    dust2::r::read_real_array(parameters, dim.diag_rec_s, diag_rec_s.data(), "diag_rec_s", true);
    std::vector<real_type> r_AU(dim.r_AU.size);
    for (size_t i = 1; i <= dim.r_AU.dim[0]; ++i) {
      for (size_t j = 1; j <= dim.r_AU.dim[1]; ++j) {
        r_AU[i - 1 + (j - 1) * dim.r_AU.mult[1]] = (mu == 0 ? nu : ((nu * mu) / (ved[j - 1] * nu + (1 - ved[j - 1]) * mu)));
      }
    }
    std::vector<real_type> Rel_U(dim.Rel_U.size);
    for (size_t i = 1; i <= dim.Rel_U.dim[0]; ++i) {
      for (size_t j = 1; j <= dim.Rel_U.dim[1]; ++j) {
        Rel_U[i - 1 + (j - 1) * dim.Rel_U.mult[1]] = ((lambda * (1 - vea[j - 1]) - D[j - 1]) == 0 ? 0 : lambda * (1 - vea[j - 1]) / (lambda * (1 - vea[j - 1]) - D[j - 1]));
      }
    }
    std::vector<real_type> Rel_I(dim.Rel_I.size);
    for (size_t i = 1; i <= dim.Rel_I.dim[0]; ++i) {
      for (size_t j = 1; j <= dim.Rel_I.dim[1]; ++j) {
        Rel_I[i - 1 + (j - 1) * dim.Rel_I.mult[1]] = (sigma - D[j - 1] == 0 ? 0 : sigma / (sigma - D[j - 1]));
      }
    }
    std::vector<real_type> Rel_S(dim.Rel_S.size);
    for (size_t i = 1; i <= dim.Rel_S.dim[0]; ++i) {
      for (size_t j = 1; j <= dim.Rel_S.dim[1]; ++j) {
        Rel_S[i - 1 + (j - 1) * dim.Rel_S.mult[1]] = (mu - D[j - 1] == 0 ? 0 : mu / (mu - D[j - 1]));
      }
    }
    std::vector<real_type> Rel_T(dim.Rel_T.size);
    for (size_t i = 1; i <= dim.Rel_T.dim[0]; ++i) {
      for (size_t j = 1; j <= dim.Rel_T.dim[1]; ++j) {
        Rel_T[i - 1 + (j - 1) * dim.Rel_T.mult[1]] = (rho - D[j - 1] == 0 ? 0 : rho / (rho - D[j - 1]));
      }
    }
    std::vector<real_type> Rel_A(dim.Rel_A.size);
    for (size_t i = 1; i <= dim.Rel_A.dim[0]; ++i) {
      for (size_t j = 1; j <= dim.Rel_A.dim[1]; ++j) {
        Rel_A[i - 1 + (j - 1) * dim.Rel_A.mult[1]] = (r_AT[i - 1 + (j - 1) * dim.r_AT.mult[1]] + r_AU[i - 1 + (j - 1) * dim.r_AU.mult[1]] - D[j - 1] == 0 ? 0 : (r_AT[i - 1 + (j - 1) * dim.r_AT.mult[1]] + r_AU[i - 1 + (j - 1) * dim.r_AU.mult[1]]) / (r_AT[i - 1 + (j - 1) * dim.r_AT.mult[1]] + r_AU[i - 1 + (j - 1) * dim.r_AU.mult[1]] - D[j - 1]));
      }
    }
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"tot_treated", {}},
      {"tot_attended", {}},
      {"U", std::vector<size_t>(dim.U.dim.begin(), dim.U.dim.end())},
      {"I", std::vector<size_t>(dim.I.dim.begin(), dim.I.dim.end())},
      {"A", std::vector<size_t>(dim.A.dim.begin(), dim.A.dim.end())},
      {"S", std::vector<size_t>(dim.S.dim.begin(), dim.S.dim.end())},
      {"T", std::vector<size_t>(dim.T.dim.begin(), dim.T.dim.end())},
      {"N", std::vector<size_t>(dim.N.dim.begin(), dim.N.dim.end())},
      {"cum_incid", std::vector<size_t>(dim.cum_incid.dim.begin(), dim.cum_incid.dim.end())},
      {"cum_diag_a", std::vector<size_t>(dim.cum_diag_a.dim.begin(), dim.cum_diag_a.dim.end())},
      {"cum_diag_s", std::vector<size_t>(dim.cum_diag_s.dim.begin(), dim.cum_diag_s.dim.end())},
      {"cum_treated", std::vector<size_t>(dim.cum_treated.dim.begin(), dim.cum_treated.dim.end())},
      {"cum_screened", std::vector<size_t>(dim.cum_screened.dim.begin(), dim.cum_screened.dim.end())},
      {"cum_pye_trial_pov", std::vector<size_t>(dim.cum_pye_trial_pov.dim.begin(), dim.cum_pye_trial_pov.dim.end())},
      {"cum_pye_noscreen_trial_pov", std::vector<size_t>(dim.cum_pye_noscreen_trial_pov.dim.begin(), dim.cum_pye_noscreen_trial_pov.dim.end())},
      {"cum_pye_true", std::vector<size_t>(dim.cum_pye_true.dim.begin(), dim.cum_pye_true.dim.end())}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, dim, n_group, n_vax, eta, sigma, psi, nu, mu, rho, lambda, r_AT, U0, I0, A0, S0, T0, vea, ved, ves, w, D, diag_rec_a, diag_rec_s, r_AU, Rel_U, Rel_I, Rel_S, Rel_T, Rel_A};
  }
  static internal_state build_internal(const shared_state& shared) {
    std::vector<real_type> screened(shared.dim.screened.size);
    std::vector<real_type> pye_trial(shared.dim.pye_trial.size);
    std::vector<real_type> pye_noscreen_trial(shared.dim.pye_noscreen_trial.size);
    std::vector<real_type> p_U_ext(shared.dim.p_U_ext.size);
    std::vector<real_type> p_I_ext(shared.dim.p_I_ext.size);
    std::vector<real_type> p_S_ext(shared.dim.p_S_ext.size);
    std::vector<real_type> p_T_ext(shared.dim.p_T_ext.size);
    std::vector<real_type> p_A_ext(shared.dim.p_A_ext.size);
    std::vector<real_type> n_U_ext(shared.dim.n_U_ext.size);
    std::vector<real_type> n_I_ext(shared.dim.n_I_ext.size);
    std::vector<real_type> n_S_ext(shared.dim.n_S_ext.size);
    std::vector<real_type> n_T_ext(shared.dim.n_T_ext.size);
    std::vector<real_type> n_A_ext(shared.dim.n_A_ext.size);
    std::vector<real_type> n_UI(shared.dim.n_UI.size);
    std::vector<real_type> n_IAS(shared.dim.n_IAS.size);
    std::vector<real_type> n_ST(shared.dim.n_ST.size);
    std::vector<real_type> n_TU(shared.dim.n_TU.size);
    std::vector<real_type> n_Uw(shared.dim.n_Uw.size);
    std::vector<real_type> n_Iw(shared.dim.n_Iw.size);
    std::vector<real_type> n_IA(shared.dim.n_IA.size);
    std::vector<real_type> n_Sw(shared.dim.n_Sw.size);
    std::vector<real_type> n_AUT(shared.dim.n_AUT.size);
    std::vector<real_type> n_Tw(shared.dim.n_Tw.size);
    std::vector<real_type> n_IS(shared.dim.n_IS.size);
    std::vector<real_type> n_Aw(shared.dim.n_Aw.size);
    std::vector<real_type> n_AT(shared.dim.n_AT.size);
    std::vector<real_type> wU(shared.dim.wU.size);
    std::vector<real_type> wI(shared.dim.wI.size);
    std::vector<real_type> wS(shared.dim.wS.size);
    std::vector<real_type> wT(shared.dim.wT.size);
    std::vector<real_type> n_AU(shared.dim.n_AU.size);
    std::vector<real_type> n_diag_rec(shared.dim.n_diag_rec.size);
    std::vector<real_type> wA(shared.dim.wA.size);
    return internal_state{screened, pye_trial, pye_noscreen_trial, p_U_ext, p_I_ext, p_S_ext, p_T_ext, p_A_ext, n_U_ext, n_I_ext, n_S_ext, n_T_ext, n_A_ext, n_UI, n_IAS, n_ST, n_TU, n_Uw, n_Iw, n_IA, n_Sw, n_AUT, n_Tw, n_IS, n_Aw, n_AT, wU, wI, wS, wT, n_AU, n_diag_rec, wA};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.eta = dust2::r::read_real(parameters, "eta", shared.eta);
    shared.sigma = dust2::r::read_real(parameters, "sigma", shared.sigma);
    shared.psi = dust2::r::read_real(parameters, "psi", shared.psi);
    shared.nu = dust2::r::read_real(parameters, "nu", shared.nu);
    shared.mu = dust2::r::read_real(parameters, "mu", shared.mu);
    shared.rho = dust2::r::read_real(parameters, "rho", shared.rho);
    shared.lambda = dust2::r::read_real(parameters, "lambda", shared.lambda);
    for (size_t i = 1; i <= shared.dim.r_AT.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.r_AT.dim[1]; ++j) {
        shared.r_AT[i - 1 + (j - 1) * shared.dim.r_AT.mult[1]] = shared.eta;
      }
    }
    dust2::r::read_real_array(parameters, shared.dim.U0, shared.U0.data(), "U0", false);
    dust2::r::read_real_array(parameters, shared.dim.I0, shared.I0.data(), "I0", false);
    dust2::r::read_real_array(parameters, shared.dim.A0, shared.A0.data(), "A0", false);
    dust2::r::read_real_array(parameters, shared.dim.S0, shared.S0.data(), "S0", false);
    dust2::r::read_real_array(parameters, shared.dim.T0, shared.T0.data(), "T0", false);
    dust2::r::read_real_array(parameters, shared.dim.vea, shared.vea.data(), "vea", false);
    dust2::r::read_real_array(parameters, shared.dim.ved, shared.ved.data(), "ved", false);
    dust2::r::read_real_array(parameters, shared.dim.ves, shared.ves.data(), "ves", false);
    dust2::r::read_real_array(parameters, shared.dim.w, shared.w.data(), "w", false);
    dust2::r::read_real_array(parameters, shared.dim.D, shared.D.data(), "D", false);
    dust2::r::read_real_array(parameters, shared.dim.diag_rec_a, shared.diag_rec_a.data(), "diag_rec_a", false);
    dust2::r::read_real_array(parameters, shared.dim.diag_rec_s, shared.diag_rec_s.data(), "diag_rec_s", false);
    for (size_t i = 1; i <= shared.dim.r_AU.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.r_AU.dim[1]; ++j) {
        shared.r_AU[i - 1 + (j - 1) * shared.dim.r_AU.mult[1]] = (shared.mu == 0 ? shared.nu : ((shared.nu * shared.mu) / (shared.ved[j - 1] * shared.nu + (1 - shared.ved[j - 1]) * shared.mu)));
      }
    }
    for (size_t i = 1; i <= shared.dim.Rel_U.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.Rel_U.dim[1]; ++j) {
        shared.Rel_U[i - 1 + (j - 1) * shared.dim.Rel_U.mult[1]] = ((shared.lambda * (1 - shared.vea[j - 1]) - shared.D[j - 1]) == 0 ? 0 : shared.lambda * (1 - shared.vea[j - 1]) / (shared.lambda * (1 - shared.vea[j - 1]) - shared.D[j - 1]));
      }
    }
    for (size_t i = 1; i <= shared.dim.Rel_I.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.Rel_I.dim[1]; ++j) {
        shared.Rel_I[i - 1 + (j - 1) * shared.dim.Rel_I.mult[1]] = (shared.sigma - shared.D[j - 1] == 0 ? 0 : shared.sigma / (shared.sigma - shared.D[j - 1]));
      }
    }
    for (size_t i = 1; i <= shared.dim.Rel_S.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.Rel_S.dim[1]; ++j) {
        shared.Rel_S[i - 1 + (j - 1) * shared.dim.Rel_S.mult[1]] = (shared.mu - shared.D[j - 1] == 0 ? 0 : shared.mu / (shared.mu - shared.D[j - 1]));
      }
    }
    for (size_t i = 1; i <= shared.dim.Rel_T.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.Rel_T.dim[1]; ++j) {
        shared.Rel_T[i - 1 + (j - 1) * shared.dim.Rel_T.mult[1]] = (shared.rho - shared.D[j - 1] == 0 ? 0 : shared.rho / (shared.rho - shared.D[j - 1]));
      }
    }
    for (size_t i = 1; i <= shared.dim.Rel_A.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.Rel_A.dim[1]; ++j) {
        shared.Rel_A[i - 1 + (j - 1) * shared.dim.Rel_A.mult[1]] = (shared.r_AT[i - 1 + (j - 1) * shared.dim.r_AT.mult[1]] + shared.r_AU[i - 1 + (j - 1) * shared.dim.r_AU.mult[1]] - shared.D[j - 1] == 0 ? 0 : (shared.r_AT[i - 1 + (j - 1) * shared.dim.r_AT.mult[1]] + shared.r_AU[i - 1 + (j - 1) * shared.dim.r_AU.mult[1]]) / (shared.r_AT[i - 1 + (j - 1) * shared.dim.r_AT.mult[1]] + shared.r_AU[i - 1 + (j - 1) * shared.dim.r_AU.mult[1]] - shared.D[j - 1]));
      }
    }
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    state[0] = 0;
    state[1] = 0;
    for (size_t i = 1; i <= shared.dim.U.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.U.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.U.mult[1] + 2] = shared.U0[i - 1 + (j - 1) * shared.dim.U0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.I.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.I.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.I.mult[1] + shared.odin.offset.state[3]] = shared.I0[i - 1 + (j - 1) * shared.dim.I0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.A.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.A.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.A.mult[1] + shared.odin.offset.state[4]] = shared.A0[i - 1 + (j - 1) * shared.dim.A0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.S.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.S.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.S.mult[1] + shared.odin.offset.state[5]] = shared.S0[i - 1 + (j - 1) * shared.dim.S0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.T.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.T.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.T.mult[1] + shared.odin.offset.state[6]] = shared.T0[i - 1 + (j - 1) * shared.dim.T0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.N.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.N.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.N.mult[1] + shared.odin.offset.state[7]] = shared.U0[i - 1 + (j - 1) * shared.dim.U0.mult[1]] + shared.I0[i - 1 + (j - 1) * shared.dim.I0.mult[1]] + shared.A0[i - 1 + (j - 1) * shared.dim.A0.mult[1]] + shared.S0[i - 1 + (j - 1) * shared.dim.S0.mult[1]] + shared.T0[i - 1 + (j - 1) * shared.dim.T0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_incid.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_incid.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_incid.mult[1] + shared.odin.offset.state[8]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_diag_a.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_diag_a.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_diag_a.mult[1] + shared.odin.offset.state[9]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_diag_s.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_diag_s.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_diag_s.mult[1] + shared.odin.offset.state[10]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_treated.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_treated.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_treated.mult[1] + shared.odin.offset.state[11]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_screened.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_screened.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_screened.mult[1] + shared.odin.offset.state[12]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_pye_trial_pov.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_pye_trial_pov.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_pye_trial_pov.mult[1] + shared.odin.offset.state[13]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_pye_noscreen_trial_pov.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_pye_noscreen_trial_pov.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_pye_noscreen_trial_pov.mult[1] + shared.odin.offset.state[14]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_pye_true.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_pye_true.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_pye_true.mult[1] + shared.odin.offset.state[15]] = 0;
      }
    }
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto * U = state + 2;
    const auto * I = state + shared.odin.offset.state[3];
    const auto * A = state + shared.odin.offset.state[4];
    const auto * S = state + shared.odin.offset.state[5];
    const auto * T = state + shared.odin.offset.state[6];
    const auto * N = state + shared.odin.offset.state[7];
    const auto * cum_incid = state + shared.odin.offset.state[8];
    const auto * cum_diag_a = state + shared.odin.offset.state[9];
    const auto * cum_diag_s = state + shared.odin.offset.state[10];
    const auto * cum_treated = state + shared.odin.offset.state[11];
    const auto * cum_screened = state + shared.odin.offset.state[12];
    const auto * cum_pye_trial_pov = state + shared.odin.offset.state[13];
    const auto * cum_pye_noscreen_trial_pov = state + shared.odin.offset.state[14];
    const auto * cum_pye_true = state + shared.odin.offset.state[15];
    for (size_t i = 1; i <= shared.dim.screened.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.screened.dim[1]; ++j) {
        internal.screened[i - 1 + (j - 1) * shared.dim.screened.mult[1]] = monty::random::binomial<real_type>(rng_state, U[i - 1 + (j - 1) * shared.dim.U.mult[1]], 1 - monty::math::exp(-shared.eta * dt));
      }
    }
    for (size_t i = 1; i <= shared.dim.pye_trial.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.pye_trial.dim[1]; ++j) {
        internal.pye_trial[i - 1 + (j - 1) * shared.dim.pye_trial.mult[1]] = (U[i - 1 + (j - 1) * shared.dim.U.mult[1]] + I[i - 1 + (j - 1) * shared.dim.I.mult[1]] + A[i - 1 + (j - 1) * shared.dim.A.mult[1]] + S[i - 1 + (j - 1) * shared.dim.S.mult[1]]) * dt;
      }
    }
    for (size_t i = 1; i <= shared.dim.pye_noscreen_trial.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.pye_noscreen_trial.dim[1]; ++j) {
        internal.pye_noscreen_trial[i - 1 + (j - 1) * shared.dim.pye_noscreen_trial.mult[1]] = (U[i - 1 + (j - 1) * shared.dim.U.mult[1]] + I[i - 1 + (j - 1) * shared.dim.I.mult[1]] + A[i - 1 + (j - 1) * shared.dim.A.mult[1]] + S[i - 1 + (j - 1) * shared.dim.S.mult[1]] + T[i - 1 + (j - 1) * shared.dim.T.mult[1]]) * dt;
      }
    }
    for (size_t i = 1; i <= shared.dim.p_U_ext.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.p_U_ext.dim[1]; ++j) {
        internal.p_U_ext[i - 1 + (j - 1) * shared.dim.p_U_ext.mult[1]] = 1 - monty::math::exp(-(shared.lambda * (1 - shared.vea[j - 1]) - shared.D[j - 1]) * dt);
      }
    }
    for (size_t i = 1; i <= shared.dim.p_I_ext.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.p_I_ext.dim[1]; ++j) {
        internal.p_I_ext[i - 1 + (j - 1) * shared.dim.p_I_ext.mult[1]] = 1 - monty::math::exp(-(shared.sigma - shared.D[j - 1]) * dt);
      }
    }
    for (size_t i = 1; i <= shared.dim.p_S_ext.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.p_S_ext.dim[1]; ++j) {
        internal.p_S_ext[i - 1 + (j - 1) * shared.dim.p_S_ext.mult[1]] = 1 - monty::math::exp(-(shared.mu - shared.D[j - 1]) * dt);
      }
    }
    for (size_t i = 1; i <= shared.dim.p_T_ext.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.p_T_ext.dim[1]; ++j) {
        internal.p_T_ext[i - 1 + (j - 1) * shared.dim.p_T_ext.mult[1]] = 1 - monty::math::exp(-(shared.rho - shared.D[j - 1]) * dt);
      }
    }
    for (size_t i = 1; i <= shared.dim.p_A_ext.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.p_A_ext.dim[1]; ++j) {
        internal.p_A_ext[i - 1 + (j - 1) * shared.dim.p_A_ext.mult[1]] = 1 - monty::math::exp(-(shared.r_AT[i - 1 + (j - 1) * shared.dim.r_AT.mult[1]] + shared.r_AU[i - 1 + (j - 1) * shared.dim.r_AU.mult[1]] - shared.D[j - 1]) * dt);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_U_ext.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_U_ext.dim[1]; ++j) {
        internal.n_U_ext[i - 1 + (j - 1) * shared.dim.n_U_ext.mult[1]] = monty::random::binomial<real_type>(rng_state, U[i - 1 + (j - 1) * shared.dim.U.mult[1]], internal.p_U_ext[i - 1 + (j - 1) * shared.dim.p_U_ext.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_I_ext.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_I_ext.dim[1]; ++j) {
        internal.n_I_ext[i - 1 + (j - 1) * shared.dim.n_I_ext.mult[1]] = monty::random::binomial<real_type>(rng_state, I[i - 1 + (j - 1) * shared.dim.I.mult[1]], internal.p_I_ext[i - 1 + (j - 1) * shared.dim.p_I_ext.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_S_ext.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_S_ext.dim[1]; ++j) {
        internal.n_S_ext[i - 1 + (j - 1) * shared.dim.n_S_ext.mult[1]] = monty::random::binomial<real_type>(rng_state, S[i - 1 + (j - 1) * shared.dim.S.mult[1]], internal.p_S_ext[i - 1 + (j - 1) * shared.dim.p_S_ext.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_T_ext.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_T_ext.dim[1]; ++j) {
        internal.n_T_ext[i - 1 + (j - 1) * shared.dim.n_T_ext.mult[1]] = monty::random::binomial<real_type>(rng_state, T[i - 1 + (j - 1) * shared.dim.T.mult[1]], internal.p_T_ext[i - 1 + (j - 1) * shared.dim.p_T_ext.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_A_ext.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_A_ext.dim[1]; ++j) {
        internal.n_A_ext[i - 1 + (j - 1) * shared.dim.n_A_ext.mult[1]] = monty::random::binomial<real_type>(rng_state, A[i - 1 + (j - 1) * shared.dim.A.mult[1]], internal.p_A_ext[i - 1 + (j - 1) * shared.dim.p_A_ext.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_UI.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_UI.dim[1]; ++j) {
        internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]] = monty::random::binomial<real_type>(rng_state, internal.n_U_ext[i - 1 + (j - 1) * shared.dim.n_U_ext.mult[1]], shared.Rel_U[i - 1 + (j - 1) * shared.dim.Rel_U.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_IAS.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_IAS.dim[1]; ++j) {
        internal.n_IAS[i - 1 + (j - 1) * shared.dim.n_IAS.mult[1]] = monty::random::binomial<real_type>(rng_state, internal.n_I_ext[i - 1 + (j - 1) * shared.dim.n_I_ext.mult[1]], shared.Rel_I[i - 1 + (j - 1) * shared.dim.Rel_I.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_ST.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_ST.dim[1]; ++j) {
        internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]] = monty::random::binomial<real_type>(rng_state, internal.n_S_ext[i - 1 + (j - 1) * shared.dim.n_S_ext.mult[1]], shared.Rel_S[i - 1 + (j - 1) * shared.dim.Rel_S.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_TU.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_TU.dim[1]; ++j) {
        internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]] = monty::random::binomial<real_type>(rng_state, internal.n_T_ext[i - 1 + (j - 1) * shared.dim.n_T_ext.mult[1]], shared.Rel_T[i - 1 + (j - 1) * shared.dim.Rel_T.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_Uw.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_Uw.dim[1]; ++j) {
        internal.n_Uw[i - 1 + (j - 1) * shared.dim.n_Uw.mult[1]] = internal.n_U_ext[i - 1 + (j - 1) * shared.dim.n_U_ext.mult[1]] - internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_Iw.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_Iw.dim[1]; ++j) {
        internal.n_Iw[i - 1 + (j - 1) * shared.dim.n_Iw.mult[1]] = internal.n_I_ext[i - 1 + (j - 1) * shared.dim.n_I_ext.mult[1]] - internal.n_IAS[i - 1 + (j - 1) * shared.dim.n_IAS.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_IA.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_IA.dim[1]; ++j) {
        internal.n_IA[i - 1 + (j - 1) * shared.dim.n_IA.mult[1]] = monty::random::binomial<real_type>(rng_state, internal.n_IAS[i - 1 + (j - 1) * shared.dim.n_IAS.mult[1]], 1 - (1 - shared.ves[j - 1]) * shared.psi);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_Sw.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_Sw.dim[1]; ++j) {
        internal.n_Sw[i - 1 + (j - 1) * shared.dim.n_Sw.mult[1]] = internal.n_S_ext[i - 1 + (j - 1) * shared.dim.n_S_ext.mult[1]] - internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_AUT.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_AUT.dim[1]; ++j) {
        internal.n_AUT[i - 1 + (j - 1) * shared.dim.n_AUT.mult[1]] = monty::random::binomial<real_type>(rng_state, internal.n_A_ext[i - 1 + (j - 1) * shared.dim.n_A_ext.mult[1]], shared.Rel_A[i - 1 + (j - 1) * shared.dim.Rel_A.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_Tw.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_Tw.dim[1]; ++j) {
        internal.n_Tw[i - 1 + (j - 1) * shared.dim.n_Tw.mult[1]] = internal.n_T_ext[i - 1 + (j - 1) * shared.dim.n_T_ext.mult[1]] - internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_IS.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_IS.dim[1]; ++j) {
        internal.n_IS[i - 1 + (j - 1) * shared.dim.n_IS.mult[1]] = internal.n_IAS[i - 1 + (j - 1) * shared.dim.n_IAS.mult[1]] - internal.n_IA[i - 1 + (j - 1) * shared.dim.n_IA.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_Aw.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_Aw.dim[1]; ++j) {
        internal.n_Aw[i - 1 + (j - 1) * shared.dim.n_Aw.mult[1]] = internal.n_A_ext[i - 1 + (j - 1) * shared.dim.n_A_ext.mult[1]] - internal.n_AUT[i - 1 + (j - 1) * shared.dim.n_AUT.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_AT.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_AT.dim[1]; ++j) {
        internal.n_AT[i - 1 + (j - 1) * shared.dim.n_AT.mult[1]] = monty::random::binomial<real_type>(rng_state, internal.n_AUT[i - 1 + (j - 1) * shared.dim.n_AUT.mult[1]], shared.r_AT[i - 1 + (j - 1) * shared.dim.r_AT.mult[1]] / (shared.r_AT[i - 1 + (j - 1) * shared.dim.r_AT.mult[1]] + shared.r_AU[i - 1 + (j - 1) * shared.dim.r_AU.mult[1]]));
      }
    }
    for (size_t i = 1; i <= shared.dim.wU.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wU.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wU.dim[2]; ++k) {
          internal.wU[i - 1 + (j - 1) * shared.dim.wU.mult[1] + (k - 1) * shared.dim.wU.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * internal.n_Uw[i - 1 + (k - 1) * shared.dim.n_Uw.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wI.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wI.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wI.dim[2]; ++k) {
          internal.wI[i - 1 + (j - 1) * shared.dim.wI.mult[1] + (k - 1) * shared.dim.wI.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * internal.n_Iw[i - 1 + (k - 1) * shared.dim.n_Iw.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wS.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wS.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wS.dim[2]; ++k) {
          internal.wS[i - 1 + (j - 1) * shared.dim.wS.mult[1] + (k - 1) * shared.dim.wS.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * internal.n_Sw[i - 1 + (k - 1) * shared.dim.n_Sw.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wT.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wT.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wT.dim[2]; ++k) {
          internal.wT[i - 1 + (j - 1) * shared.dim.wT.mult[1] + (k - 1) * shared.dim.wT.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * internal.n_Tw[i - 1 + (k - 1) * shared.dim.n_Tw.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.n_AU.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_AU.dim[1]; ++j) {
        internal.n_AU[i - 1 + (j - 1) * shared.dim.n_AU.mult[1]] = internal.n_AUT[i - 1 + (j - 1) * shared.dim.n_AUT.mult[1]] - internal.n_AT[i - 1 + (j - 1) * shared.dim.n_AT.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_diag_rec.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_diag_rec.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.n_diag_rec.dim[2]; ++k) {
          internal.n_diag_rec[i - 1 + (j - 1) * shared.dim.n_diag_rec.mult[1] + (k - 1) * shared.dim.n_diag_rec.mult[2]] = (shared.diag_rec_s[i - 1 + (j - 1) * shared.dim.diag_rec_s.mult[1] + (k - 1) * shared.dim.diag_rec_s.mult[2]] * internal.n_ST[i - 1 + (k - 1) * shared.dim.n_ST.mult[1]]) + (shared.diag_rec_a[i - 1 + (j - 1) * shared.dim.diag_rec_a.mult[1] + (k - 1) * shared.dim.diag_rec_a.mult[2]] * internal.n_AT[i - 1 + (k - 1) * shared.dim.n_AT.mult[1]]);
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wA.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wA.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wA.dim[2]; ++k) {
          internal.wA[i - 1 + (j - 1) * shared.dim.wA.mult[1] + (k - 1) * shared.dim.wA.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * internal.n_Aw[i - 1 + (k - 1) * shared.dim.n_Aw.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.U.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.U.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.U.mult[1] + 2] = U[i - 1 + (j - 1) * shared.dim.U.mult[1]] - internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]] + internal.n_AU[i - 1 + (j - 1) * shared.dim.n_AU.mult[1]] + internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]] + dust2::array::sum<real_type>(internal.wU.data(), shared.dim.wU, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wU.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.I.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.I.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.I.mult[1] + shared.odin.offset.state[3]] = I[i - 1 + (j - 1) * shared.dim.I.mult[1]] + internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]] - internal.n_IAS[i - 1 + (j - 1) * shared.dim.n_IAS.mult[1]] + dust2::array::sum<real_type>(internal.wI.data(), shared.dim.wI, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wI.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.A.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.A.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.A.mult[1] + shared.odin.offset.state[4]] = A[i - 1 + (j - 1) * shared.dim.A.mult[1]] + internal.n_IA[i - 1 + (j - 1) * shared.dim.n_IA.mult[1]] - internal.n_AUT[i - 1 + (j - 1) * shared.dim.n_AUT.mult[1]] + dust2::array::sum<real_type>(internal.wA.data(), shared.dim.wA, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wA.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.S.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.S.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.S.mult[1] + shared.odin.offset.state[5]] = S[i - 1 + (j - 1) * shared.dim.S.mult[1]] + internal.n_IS[i - 1 + (j - 1) * shared.dim.n_IS.mult[1]] - internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]] + dust2::array::sum<real_type>(internal.wS.data(), shared.dim.wS, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wS.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.T.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.T.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.T.mult[1] + shared.odin.offset.state[6]] = T[i - 1 + (j - 1) * shared.dim.T.mult[1]] + internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]] + internal.n_AT[i - 1 + (j - 1) * shared.dim.n_AT.mult[1]] - internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]] + dust2::array::sum<real_type>(internal.wT.data(), shared.dim.wT, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wT.dim[2] - 1}) - dust2::array::sum<real_type>(internal.n_diag_rec.data(), shared.dim.n_diag_rec, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.n_diag_rec.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_incid.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_incid.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.cum_incid.mult[1] + shared.odin.offset.state[8]] = cum_incid[i - 1 + (j - 1) * shared.dim.cum_incid.mult[1]] + internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_diag_a.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_diag_a.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.cum_diag_a.mult[1] + shared.odin.offset.state[9]] = cum_diag_a[i - 1 + (j - 1) * shared.dim.cum_diag_a.mult[1]] + internal.n_AT[i - 1 + (j - 1) * shared.dim.n_AT.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_diag_s.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_diag_s.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.cum_diag_s.mult[1] + shared.odin.offset.state[10]] = cum_diag_s[i - 1 + (j - 1) * shared.dim.cum_diag_s.mult[1]] + internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_treated.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_treated.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.cum_treated.mult[1] + shared.odin.offset.state[11]] = cum_treated[i - 1 + (j - 1) * shared.dim.cum_treated.mult[1]] + internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_screened.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_screened.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.cum_screened.mult[1] + shared.odin.offset.state[12]] = cum_screened[i - 1 + (j - 1) * shared.dim.cum_screened.mult[1]] + internal.screened[i - 1 + (j - 1) * shared.dim.screened.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_pye_trial_pov.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_pye_trial_pov.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.cum_pye_trial_pov.mult[1] + shared.odin.offset.state[13]] = cum_pye_trial_pov[i - 1 + (j - 1) * shared.dim.cum_pye_trial_pov.mult[1]] + internal.pye_trial[i - 1 + (j - 1) * shared.dim.pye_trial.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_pye_noscreen_trial_pov.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_pye_noscreen_trial_pov.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.cum_pye_noscreen_trial_pov.mult[1] + shared.odin.offset.state[14]] = cum_pye_noscreen_trial_pov[i - 1 + (j - 1) * shared.dim.cum_pye_noscreen_trial_pov.mult[1]] + internal.pye_noscreen_trial[i - 1 + (j - 1) * shared.dim.pye_noscreen_trial.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_pye_true.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_pye_true.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.cum_pye_true.mult[1] + shared.odin.offset.state[15]] = cum_pye_true[i - 1 + (j - 1) * shared.dim.cum_pye_true.mult[1]] + (U[i - 1 + (j - 1) * shared.dim.U.mult[1]] * dt);
      }
    }
    state_next[0] = dust2::array::sum<real_type>(cum_treated, shared.dim.cum_treated);
    state_next[1] = dust2::array::sum<real_type>(cum_treated, shared.dim.cum_treated) + dust2::array::sum<real_type>(cum_screened, shared.dim.cum_screened);
    for (size_t i = 1; i <= shared.dim.N.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.N.dim[1]; ++j) {
        state_next[i - 1 + (j - 1) * shared.dim.N.mult[1] + shared.odin.offset.state[7]] = N[i - 1 + (j - 1) * shared.dim.N.mult[1]] + dust2::array::sum<real_type>(internal.wU.data(), shared.dim.wU, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wU.dim[2] - 1}) + dust2::array::sum<real_type>(internal.wI.data(), shared.dim.wI, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wI.dim[2] - 1}) + dust2::array::sum<real_type>(internal.wA.data(), shared.dim.wA, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wA.dim[2] - 1}) + dust2::array::sum<real_type>(internal.wS.data(), shared.dim.wS, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wS.dim[2] - 1}) + dust2::array::sum<real_type>(internal.wT.data(), shared.dim.wT, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wT.dim[2] - 1}) - dust2::array::sum<real_type>(internal.n_diag_rec.data(), shared.dim.n_diag_rec, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.n_diag_rec.dim[2] - 1});
      }
    }
  }
};
