// Generated by odin2 (version 0.3.21) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(model_withoutPN)]]
// [[dust2::time_type(continuous)]]
// [[dust2::parameter(n_vax, type = "int", rank = 0, required = FALSE, constant = TRUE)]]
// [[dust2::parameter(tt, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(U0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(I0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(A0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(S0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(T0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(p, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(q, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(willing, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(enr, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(exr, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(beta_t, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(eta_l_t, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(eta_h_t, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(epsilon, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(sigma, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(psi, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(nu, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(mu, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(rho, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vbe, type = "real_type", rank = 3, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vos, type = "real_type", rank = 3, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vod, type = "real_type", rank = 3, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vea, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(ved, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(ves, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vei, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(u_vbe, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(u_d, type = "real_type", rank = 3, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(u_s, type = "real_type", rank = 3, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(w, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vax_t, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vax_y, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(wd, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(diag_rec, type = "real_type", rank = 3, required = TRUE, constant = FALSE)]]
class model_withoutPN {
public:
  model_withoutPN() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 22> state;
      } offset;
    } odin;
    struct dim_type {
      dust2::array::dimensions<1> tt;
      dust2::array::dimensions<2> U;
      dust2::array::dimensions<2> I;
      dust2::array::dimensions<2> A;
      dust2::array::dimensions<2> S;
      dust2::array::dimensions<2> T;
      dust2::array::dimensions<2> U0;
      dust2::array::dimensions<2> I0;
      dust2::array::dimensions<2> A0;
      dust2::array::dimensions<2> S0;
      dust2::array::dimensions<2> T0;
      dust2::array::dimensions<2> C;
      dust2::array::dimensions<2> N;
      dust2::array::dimensions<2> entrants;
      dust2::array::dimensions<1> Np;
      dust2::array::dimensions<1> prop_C;
      dust2::array::dimensions<1> foi_LH;
      dust2::array::dimensions<1> lambda;
      dust2::array::dimensions<2> n_UI;
      dust2::array::dimensions<2> n_AT;
      dust2::array::dimensions<2> n_AU;
      dust2::array::dimensions<2> n_ST;
      dust2::array::dimensions<2> n_TU;
      dust2::array::dimensions<2> screened;
      dust2::array::dimensions<2> cum_incid;
      dust2::array::dimensions<2> cum_diag_a;
      dust2::array::dimensions<2> cum_diag_s;
      dust2::array::dimensions<2> cum_treated;
      dust2::array::dimensions<2> cum_screened;
      dust2::array::dimensions<2> cum_offered;
      dust2::array::dimensions<2> cum_vaccinated;
      dust2::array::dimensions<2> cum_vaccinated_screen;
      dust2::array::dimensions<2> cum_vbe;
      dust2::array::dimensions<2> cum_offered_vbe;
      dust2::array::dimensions<2> cum_entrants;
      dust2::array::dimensions<3> n_diag_rec;
      dust2::array::dimensions<3> diag_rec;
      dust2::array::dimensions<1> beta_t;
      dust2::array::dimensions<1> eta_l_t;
      dust2::array::dimensions<1> eta_h_t;
      dust2::array::dimensions<1> p;
      dust2::array::dimensions<1> q;
      dust2::array::dimensions<1> eta;
      dust2::array::dimensions<1> vea;
      dust2::array::dimensions<1> ved;
      dust2::array::dimensions<1> ves;
      dust2::array::dimensions<1> vei;
      dust2::array::dimensions<1> willing;
      dust2::array::dimensions<3> vbe;
      dust2::array::dimensions<3> vod;
      dust2::array::dimensions<3> vos;
      dust2::array::dimensions<2> w;
      dust2::array::dimensions<3> u_d;
      dust2::array::dimensions<3> u_s;
      dust2::array::dimensions<1> vax_t;
      dust2::array::dimensions<1> vax_y;
      dust2::array::dimensions<3> n_vbe;
      dust2::array::dimensions<3> n_vos;
      dust2::array::dimensions<3> n_vod;
      dust2::array::dimensions<3> n_obe;
      dust2::array::dimensions<3> n_oos;
      dust2::array::dimensions<3> n_ood;
      dust2::array::dimensions<3> wU;
      dust2::array::dimensions<3> wI;
      dust2::array::dimensions<3> wA;
      dust2::array::dimensions<3> wS;
      dust2::array::dimensions<3> wT;
      dust2::array::dimensions<2> wd;
      dust2::array::dimensions<3> wdU;
      dust2::array::dimensions<3> wdI;
      dust2::array::dimensions<3> wdA;
      dust2::array::dimensions<3> wdS;
      dust2::array::dimensions<3> wdT;
    } dim;
    real_type n_group;
    int n_vax;
    real_type enr;
    real_type exr;
    real_type epsilon;
    real_type sigma;
    real_type psi;
    real_type nu;
    real_type mu;
    real_type rho;
    real_type u_vbe;
    std::vector<real_type> tt;
    std::vector<real_type> vax_t;
    std::vector<real_type> vax_y;
    dust2::interpolate::InterpolateConstant<real_type> interpolate_vax_switch;
    std::vector<real_type> U0;
    std::vector<real_type> I0;
    std::vector<real_type> A0;
    std::vector<real_type> S0;
    std::vector<real_type> T0;
    std::vector<real_type> p;
    std::vector<real_type> q;
    std::vector<real_type> willing;
    std::vector<real_type> beta_t;
    std::vector<real_type> eta_l_t;
    std::vector<real_type> eta_h_t;
    std::vector<real_type> vbe;
    std::vector<real_type> vos;
    std::vector<real_type> vod;
    std::vector<real_type> vea;
    std::vector<real_type> ved;
    std::vector<real_type> ves;
    std::vector<real_type> vei;
    std::vector<real_type> u_d;
    std::vector<real_type> u_s;
    std::vector<real_type> w;
    std::vector<real_type> wd;
    std::vector<real_type> diag_rec;
    dust2::interpolate::InterpolateLinear<real_type> interpolate_beta;
    dust2::interpolate::InterpolateLinear<real_type> interpolate_eta_l;
    dust2::interpolate::InterpolateLinear<real_type> interpolate_eta_h;
    std::vector<real_type> entrants;
    std::vector<real_type> n_obe;
    std::vector<real_type> n_vbe;
  };
  struct internal_state {
    std::vector<real_type> N;
    std::vector<real_type> n_ST;
    std::vector<real_type> n_TU;
    std::vector<real_type> C;
    std::vector<real_type> Np;
    std::vector<real_type> n_AU;
    std::vector<real_type> n_diag_rec;
    std::vector<real_type> wU;
    std::vector<real_type> wI;
    std::vector<real_type> wA;
    std::vector<real_type> wS;
    std::vector<real_type> wT;
    std::vector<real_type> wdU;
    std::vector<real_type> wdI;
    std::vector<real_type> wdA;
    std::vector<real_type> wdS;
    std::vector<real_type> wdT;
    std::vector<real_type> prop_C;
    std::vector<real_type> n_ood;
    std::vector<real_type> eta;
    std::vector<real_type> foi_LH;
    std::vector<real_type> n_vod;
    std::vector<real_type> lambda;
    std::vector<real_type> n_AT;
    std::vector<real_type> screened;
    std::vector<real_type> n_UI;
    std::vector<real_type> n_oos;
    std::vector<real_type> n_vos;
  };
  using data_type = dust2::no_data;
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    shared_state::dim_type dim;
    const real_type n_group = 2;
    const int n_vax = dust2::r::read_int(parameters, "n_vax", 1);
    dim.tt = dust2::r::read_dimensions<1>(parameters, "tt");
    const real_type enr = dust2::r::read_real(parameters, "enr");
    const real_type exr = dust2::r::read_real(parameters, "exr");
    const real_type epsilon = dust2::r::read_real(parameters, "epsilon");
    const real_type sigma = dust2::r::read_real(parameters, "sigma");
    const real_type psi = dust2::r::read_real(parameters, "psi");
    const real_type nu = dust2::r::read_real(parameters, "nu");
    const real_type mu = dust2::r::read_real(parameters, "mu");
    const real_type rho = dust2::r::read_real(parameters, "rho");
    const real_type u_vbe = dust2::r::read_real(parameters, "u_vbe");
    dim.vax_t = dust2::r::read_dimensions<1>(parameters, "vax_t");
    dim.vax_y = dust2::r::read_dimensions<1>(parameters, "vax_y");
    std::vector<real_type> tt(dim.tt.size);
    dust2::r::read_real_array(parameters, dim.tt, tt.data(), "tt", true);
    dim.U.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.I.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.A.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.S.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.T.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.U0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.I0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.A0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.S0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.T0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.C.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.N.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.entrants.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.Np.set({static_cast<size_t>(n_group)});
    dim.prop_C.set({static_cast<size_t>(n_group)});
    dim.foi_LH.set({static_cast<size_t>(n_group)});
    dim.lambda.set({static_cast<size_t>(n_group)});
    dim.n_UI.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_AT.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_AU.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_ST.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_TU.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.screened.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_incid.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_diag_a.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_diag_s.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_treated.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_screened.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_offered.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_vaccinated.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_vaccinated_screen.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_vbe.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_offered_vbe.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_entrants.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_diag_rec.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.diag_rec.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    std::vector<real_type> vax_t(dim.vax_t.size);
    dust2::r::read_real_array(parameters, dim.vax_t, vax_t.data(), "vax_t", true);
    std::vector<real_type> vax_y(dim.vax_y.size);
    dust2::r::read_real_array(parameters, dim.vax_y, vax_y.data(), "vax_y", true);
    dim.beta_t.set({static_cast<size_t>(dim.tt.size)});
    dim.eta_l_t.set({static_cast<size_t>(dim.tt.size)});
    dim.eta_h_t.set({static_cast<size_t>(dim.tt.size)});
    dim.p.set({static_cast<size_t>(n_group)});
    dim.q.set({static_cast<size_t>(n_group)});
    dim.eta.set({static_cast<size_t>(n_group)});
    dim.vea.set({static_cast<size_t>(n_vax)});
    dim.ved.set({static_cast<size_t>(n_vax)});
    dim.ves.set({static_cast<size_t>(n_vax)});
    dim.vei.set({static_cast<size_t>(n_vax)});
    dim.willing.set({static_cast<size_t>(n_vax)});
    dim.vbe.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.vod.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.vos.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.w.set({static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.u_d.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.u_s.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.n_vbe.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.n_vos.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.n_vod.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.n_obe.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.n_oos.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.n_ood.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wU.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wI.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wA.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wS.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wT.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wd.set({static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wdU.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wdI.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wdA.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wdS.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wdT.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    const auto interpolate_vax_switch = dust2::interpolate::InterpolateConstant(vax_t, vax_y, "vax_t", "vax_y");
    std::vector<real_type> U0(dim.U0.size);
    dust2::r::read_real_array(parameters, dim.U0, U0.data(), "U0", true);
    std::vector<real_type> I0(dim.I0.size);
    dust2::r::read_real_array(parameters, dim.I0, I0.data(), "I0", true);
    std::vector<real_type> A0(dim.A0.size);
    dust2::r::read_real_array(parameters, dim.A0, A0.data(), "A0", true);
    std::vector<real_type> S0(dim.S0.size);
    dust2::r::read_real_array(parameters, dim.S0, S0.data(), "S0", true);
    std::vector<real_type> T0(dim.T0.size);
    dust2::r::read_real_array(parameters, dim.T0, T0.data(), "T0", true);
    std::vector<real_type> p(dim.p.size);
    dust2::r::read_real_array(parameters, dim.p, p.data(), "p", true);
    std::vector<real_type> q(dim.q.size);
    dust2::r::read_real_array(parameters, dim.q, q.data(), "q", true);
    std::vector<real_type> willing(dim.willing.size);
    dust2::r::read_real_array(parameters, dim.willing, willing.data(), "willing", true);
    std::vector<real_type> beta_t(dim.beta_t.size);
    dust2::r::read_real_array(parameters, dim.beta_t, beta_t.data(), "beta_t", true);
    std::vector<real_type> eta_l_t(dim.eta_l_t.size);
    dust2::r::read_real_array(parameters, dim.eta_l_t, eta_l_t.data(), "eta_l_t", true);
    std::vector<real_type> eta_h_t(dim.eta_h_t.size);
    dust2::r::read_real_array(parameters, dim.eta_h_t, eta_h_t.data(), "eta_h_t", true);
    std::vector<real_type> vbe(dim.vbe.size);
    dust2::r::read_real_array(parameters, dim.vbe, vbe.data(), "vbe", true);
    std::vector<real_type> vos(dim.vos.size);
    dust2::r::read_real_array(parameters, dim.vos, vos.data(), "vos", true);
    std::vector<real_type> vod(dim.vod.size);
    dust2::r::read_real_array(parameters, dim.vod, vod.data(), "vod", true);
    std::vector<real_type> vea(dim.vea.size);
    dust2::r::read_real_array(parameters, dim.vea, vea.data(), "vea", true);
    std::vector<real_type> ved(dim.ved.size);
    dust2::r::read_real_array(parameters, dim.ved, ved.data(), "ved", true);
    std::vector<real_type> ves(dim.ves.size);
    dust2::r::read_real_array(parameters, dim.ves, ves.data(), "ves", true);
    std::vector<real_type> vei(dim.vei.size);
    dust2::r::read_real_array(parameters, dim.vei, vei.data(), "vei", true);
    std::vector<real_type> u_d(dim.u_d.size);
    dust2::r::read_real_array(parameters, dim.u_d, u_d.data(), "u_d", true);
    std::vector<real_type> u_s(dim.u_s.size);
    dust2::r::read_real_array(parameters, dim.u_s, u_s.data(), "u_s", true);
    std::vector<real_type> w(dim.w.size);
    dust2::r::read_real_array(parameters, dim.w, w.data(), "w", true);
    std::vector<real_type> wd(dim.wd.size);
    dust2::r::read_real_array(parameters, dim.wd, wd.data(), "wd", true);
    std::vector<real_type> diag_rec(dim.diag_rec.size);
    dust2::r::read_real_array(parameters, dim.diag_rec, diag_rec.data(), "diag_rec", true);
    const auto interpolate_beta = dust2::interpolate::InterpolateLinear(tt, beta_t, "tt", "beta_t");
    const auto interpolate_eta_l = dust2::interpolate::InterpolateLinear(tt, eta_l_t, "tt", "eta_l_t");
    const auto interpolate_eta_h = dust2::interpolate::InterpolateLinear(tt, eta_h_t, "tt", "eta_h_t");
    std::vector<real_type> entrants(dim.entrants.size);
    for (size_t i = 1; i <= dim.entrants.dim[0]; ++i) {
      for (size_t j = 1; j <= dim.entrants.dim[1]; ++j) {
        entrants[i - 1 + (j - 1) * dim.entrants.mult[1]] = enr * q[i - 1] * willing[j - 1];
      }
    }
    std::vector<real_type> n_obe(dim.n_obe.size);
    for (size_t i = 1; i <= dim.n_obe.dim[0]; ++i) {
      for (size_t j = 1; j <= dim.n_obe.dim[1]; ++j) {
        for (size_t k = 1; k <= dim.n_obe.dim[2]; ++k) {
          n_obe[i - 1 + (j - 1) * dim.n_obe.mult[1] + (k - 1) * dim.n_obe.mult[2]] = vbe[i - 1 + (j - 1) * dim.vbe.mult[1] + (k - 1) * dim.vbe.mult[2]] * entrants[i - 1 + (k - 1) * dim.entrants.mult[1]];
        }
      }
    }
    std::vector<real_type> n_vbe(dim.n_vbe.size);
    for (size_t i = 1; i <= dim.n_vbe.dim[0]; ++i) {
      for (size_t j = 1; j <= dim.n_vbe.dim[1]; ++j) {
        for (size_t k = 1; k <= dim.n_vbe.dim[2]; ++k) {
          n_vbe[i - 1 + (j - 1) * dim.n_vbe.mult[1] + (k - 1) * dim.n_vbe.mult[2]] = n_obe[i - 1 + (j - 1) * dim.n_obe.mult[1] + (k - 1) * dim.n_obe.mult[2]] * u_vbe;
        }
      }
    }
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"U", std::vector<size_t>(dim.U.dim.begin(), dim.U.dim.end())},
      {"I", std::vector<size_t>(dim.I.dim.begin(), dim.I.dim.end())},
      {"A", std::vector<size_t>(dim.A.dim.begin(), dim.A.dim.end())},
      {"S", std::vector<size_t>(dim.S.dim.begin(), dim.S.dim.end())},
      {"T", std::vector<size_t>(dim.T.dim.begin(), dim.T.dim.end())},
      {"cum_incid", std::vector<size_t>(dim.cum_incid.dim.begin(), dim.cum_incid.dim.end())},
      {"cum_diag_a", std::vector<size_t>(dim.cum_diag_a.dim.begin(), dim.cum_diag_a.dim.end())},
      {"cum_diag_s", std::vector<size_t>(dim.cum_diag_s.dim.begin(), dim.cum_diag_s.dim.end())},
      {"cum_treated", std::vector<size_t>(dim.cum_treated.dim.begin(), dim.cum_treated.dim.end())},
      {"cum_screened", std::vector<size_t>(dim.cum_screened.dim.begin(), dim.cum_screened.dim.end())},
      {"cum_offered", std::vector<size_t>(dim.cum_offered.dim.begin(), dim.cum_offered.dim.end())},
      {"cum_vaccinated", std::vector<size_t>(dim.cum_vaccinated.dim.begin(), dim.cum_vaccinated.dim.end())},
      {"cum_vaccinated_screen", std::vector<size_t>(dim.cum_vaccinated_screen.dim.begin(), dim.cum_vaccinated_screen.dim.end())},
      {"cum_vbe", std::vector<size_t>(dim.cum_vbe.dim.begin(), dim.cum_vbe.dim.end())},
      {"cum_offered_vbe", std::vector<size_t>(dim.cum_offered_vbe.dim.begin(), dim.cum_offered_vbe.dim.end())},
      {"cum_entrants", std::vector<size_t>(dim.cum_entrants.dim.begin(), dim.cum_entrants.dim.end())},
      {"tot_treated", {}},
      {"tot_attended", {}},
      {"beta", {}},
      {"eta", std::vector<size_t>(dim.eta.dim.begin(), dim.eta.dim.end())},
      {"N", std::vector<size_t>(dim.N.dim.begin(), dim.N.dim.end())},
      {"lambda", std::vector<size_t>(dim.lambda.dim.begin(), dim.lambda.dim.end())}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, dim, n_group, n_vax, enr, exr, epsilon, sigma, psi, nu, mu, rho, u_vbe, tt, vax_t, vax_y, interpolate_vax_switch, U0, I0, A0, S0, T0, p, q, willing, beta_t, eta_l_t, eta_h_t, vbe, vos, vod, vea, ved, ves, vei, u_d, u_s, w, wd, diag_rec, interpolate_beta, interpolate_eta_l, interpolate_eta_h, entrants, n_obe, n_vbe};
  }
  static internal_state build_internal(const shared_state& shared) {
    std::vector<real_type> N(shared.dim.N.size);
    std::vector<real_type> n_ST(shared.dim.n_ST.size);
    std::vector<real_type> n_TU(shared.dim.n_TU.size);
    std::vector<real_type> C(shared.dim.C.size);
    std::vector<real_type> Np(shared.dim.Np.size);
    std::vector<real_type> n_AU(shared.dim.n_AU.size);
    std::vector<real_type> n_diag_rec(shared.dim.n_diag_rec.size);
    std::vector<real_type> wU(shared.dim.wU.size);
    std::vector<real_type> wI(shared.dim.wI.size);
    std::vector<real_type> wA(shared.dim.wA.size);
    std::vector<real_type> wS(shared.dim.wS.size);
    std::vector<real_type> wT(shared.dim.wT.size);
    std::vector<real_type> wdU(shared.dim.wdU.size);
    std::vector<real_type> wdI(shared.dim.wdI.size);
    std::vector<real_type> wdA(shared.dim.wdA.size);
    std::vector<real_type> wdS(shared.dim.wdS.size);
    std::vector<real_type> wdT(shared.dim.wdT.size);
    std::vector<real_type> prop_C(shared.dim.prop_C.size);
    std::vector<real_type> n_ood(shared.dim.n_ood.size);
    std::vector<real_type> eta(shared.dim.eta.size);
    std::vector<real_type> foi_LH(shared.dim.foi_LH.size);
    std::vector<real_type> n_vod(shared.dim.n_vod.size);
    std::vector<real_type> lambda(shared.dim.lambda.size);
    std::vector<real_type> n_AT(shared.dim.n_AT.size);
    std::vector<real_type> screened(shared.dim.screened.size);
    std::vector<real_type> n_UI(shared.dim.n_UI.size);
    std::vector<real_type> n_oos(shared.dim.n_oos.size);
    std::vector<real_type> n_vos(shared.dim.n_vos.size);
    return internal_state{N, n_ST, n_TU, C, Np, n_AU, n_diag_rec, wU, wI, wA, wS, wT, wdU, wdI, wdA, wdS, wdT, prop_C, n_ood, eta, foi_LH, n_vod, lambda, n_AT, screened, n_UI, n_oos, n_vos};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.enr = dust2::r::read_real(parameters, "enr", shared.enr);
    shared.exr = dust2::r::read_real(parameters, "exr", shared.exr);
    shared.epsilon = dust2::r::read_real(parameters, "epsilon", shared.epsilon);
    shared.sigma = dust2::r::read_real(parameters, "sigma", shared.sigma);
    shared.psi = dust2::r::read_real(parameters, "psi", shared.psi);
    shared.nu = dust2::r::read_real(parameters, "nu", shared.nu);
    shared.mu = dust2::r::read_real(parameters, "mu", shared.mu);
    shared.rho = dust2::r::read_real(parameters, "rho", shared.rho);
    shared.u_vbe = dust2::r::read_real(parameters, "u_vbe", shared.u_vbe);
    dust2::r::read_real_array(parameters, shared.dim.tt, shared.tt.data(), "tt", false);
    dust2::r::read_real_array(parameters, shared.dim.vax_t, shared.vax_t.data(), "vax_t", false);
    dust2::r::read_real_array(parameters, shared.dim.vax_y, shared.vax_y.data(), "vax_y", false);
    const auto interpolate_vax_switch = dust2::interpolate::InterpolateConstant(shared.vax_t, shared.vax_y, "vax_t", "vax_y");
    dust2::r::read_real_array(parameters, shared.dim.U0, shared.U0.data(), "U0", false);
    dust2::r::read_real_array(parameters, shared.dim.I0, shared.I0.data(), "I0", false);
    dust2::r::read_real_array(parameters, shared.dim.A0, shared.A0.data(), "A0", false);
    dust2::r::read_real_array(parameters, shared.dim.S0, shared.S0.data(), "S0", false);
    dust2::r::read_real_array(parameters, shared.dim.T0, shared.T0.data(), "T0", false);
    dust2::r::read_real_array(parameters, shared.dim.p, shared.p.data(), "p", false);
    dust2::r::read_real_array(parameters, shared.dim.q, shared.q.data(), "q", false);
    dust2::r::read_real_array(parameters, shared.dim.willing, shared.willing.data(), "willing", false);
    dust2::r::read_real_array(parameters, shared.dim.beta_t, shared.beta_t.data(), "beta_t", false);
    dust2::r::read_real_array(parameters, shared.dim.eta_l_t, shared.eta_l_t.data(), "eta_l_t", false);
    dust2::r::read_real_array(parameters, shared.dim.eta_h_t, shared.eta_h_t.data(), "eta_h_t", false);
    dust2::r::read_real_array(parameters, shared.dim.vbe, shared.vbe.data(), "vbe", false);
    dust2::r::read_real_array(parameters, shared.dim.vos, shared.vos.data(), "vos", false);
    dust2::r::read_real_array(parameters, shared.dim.vod, shared.vod.data(), "vod", false);
    dust2::r::read_real_array(parameters, shared.dim.vea, shared.vea.data(), "vea", false);
    dust2::r::read_real_array(parameters, shared.dim.ved, shared.ved.data(), "ved", false);
    dust2::r::read_real_array(parameters, shared.dim.ves, shared.ves.data(), "ves", false);
    dust2::r::read_real_array(parameters, shared.dim.vei, shared.vei.data(), "vei", false);
    dust2::r::read_real_array(parameters, shared.dim.u_d, shared.u_d.data(), "u_d", false);
    dust2::r::read_real_array(parameters, shared.dim.u_s, shared.u_s.data(), "u_s", false);
    dust2::r::read_real_array(parameters, shared.dim.w, shared.w.data(), "w", false);
    dust2::r::read_real_array(parameters, shared.dim.wd, shared.wd.data(), "wd", false);
    dust2::r::read_real_array(parameters, shared.dim.diag_rec, shared.diag_rec.data(), "diag_rec", false);
    const auto interpolate_beta = dust2::interpolate::InterpolateLinear(shared.tt, shared.beta_t, "tt", "beta_t");
    const auto interpolate_eta_l = dust2::interpolate::InterpolateLinear(shared.tt, shared.eta_l_t, "tt", "eta_l_t");
    const auto interpolate_eta_h = dust2::interpolate::InterpolateLinear(shared.tt, shared.eta_h_t, "tt", "eta_h_t");
    for (size_t i = 1; i <= shared.dim.entrants.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.entrants.dim[1]; ++j) {
        shared.entrants[i - 1 + (j - 1) * shared.dim.entrants.mult[1]] = shared.enr * shared.q[i - 1] * shared.willing[j - 1];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_obe.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_obe.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.n_obe.dim[2]; ++k) {
          shared.n_obe[i - 1 + (j - 1) * shared.dim.n_obe.mult[1] + (k - 1) * shared.dim.n_obe.mult[2]] = shared.vbe[i - 1 + (j - 1) * shared.dim.vbe.mult[1] + (k - 1) * shared.dim.vbe.mult[2]] * shared.entrants[i - 1 + (k - 1) * shared.dim.entrants.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.n_vbe.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_vbe.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.n_vbe.dim[2]; ++k) {
          shared.n_vbe[i - 1 + (j - 1) * shared.dim.n_vbe.mult[1] + (k - 1) * shared.dim.n_vbe.mult[2]] = shared.n_obe[i - 1 + (j - 1) * shared.dim.n_obe.mult[1] + (k - 1) * shared.dim.n_obe.mult[2]] * shared.u_vbe;
        }
      }
    }
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    for (size_t i = 1; i <= shared.dim.U.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.U.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.U.mult[1] + 0] = shared.U0[i - 1 + (j - 1) * shared.dim.U0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.I.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.I.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.I.mult[1] + shared.odin.offset.state[1]] = shared.I0[i - 1 + (j - 1) * shared.dim.I0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.A.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.A.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.A.mult[1] + shared.odin.offset.state[2]] = shared.A0[i - 1 + (j - 1) * shared.dim.A0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.S.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.S.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.S.mult[1] + shared.odin.offset.state[3]] = shared.S0[i - 1 + (j - 1) * shared.dim.S0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.T.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.T.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.T.mult[1] + shared.odin.offset.state[4]] = shared.T0[i - 1 + (j - 1) * shared.dim.T0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_incid.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_incid.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_incid.mult[1] + shared.odin.offset.state[5]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_diag_a.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_diag_a.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_diag_a.mult[1] + shared.odin.offset.state[6]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_diag_s.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_diag_s.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_diag_s.mult[1] + shared.odin.offset.state[7]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_treated.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_treated.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_treated.mult[1] + shared.odin.offset.state[8]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_screened.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_screened.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_screened.mult[1] + shared.odin.offset.state[9]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_offered.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_offered.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_offered.mult[1] + shared.odin.offset.state[10]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_vaccinated.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_vaccinated.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_vaccinated.mult[1] + shared.odin.offset.state[11]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_vaccinated_screen.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_vaccinated_screen.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_vaccinated_screen.mult[1] + shared.odin.offset.state[12]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_vbe.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_vbe.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_vbe.mult[1] + shared.odin.offset.state[13]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_offered_vbe.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_offered_vbe.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_offered_vbe.mult[1] + shared.odin.offset.state[14]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_entrants.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_entrants.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_entrants.mult[1] + shared.odin.offset.state[15]] = 0;
      }
    }
  }
  static void rhs(real_type time, const real_type* state, const shared_state& shared, internal_state& internal, real_type* state_deriv) {
    const auto * U = state + 0;
    const auto * I = state + shared.odin.offset.state[1];
    const auto * A = state + shared.odin.offset.state[2];
    const auto * S = state + shared.odin.offset.state[3];
    const auto * T = state + shared.odin.offset.state[4];
    for (size_t i = 1; i <= shared.dim.N.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.N.dim[1]; ++j) {
        internal.N[i - 1 + (j - 1) * shared.dim.N.mult[1]] = U[i - 1 + (j - 1) * shared.dim.U.mult[1]] + I[i - 1 + (j - 1) * shared.dim.I.mult[1]] + A[i - 1 + (j - 1) * shared.dim.A.mult[1]] + S[i - 1 + (j - 1) * shared.dim.S.mult[1]] + T[i - 1 + (j - 1) * shared.dim.T.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_ST.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_ST.dim[1]; ++j) {
        internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]] = shared.mu * S[i - 1 + (j - 1) * shared.dim.S.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_TU.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_TU.dim[1]; ++j) {
        internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]] = shared.rho * T[i - 1 + (j - 1) * shared.dim.T.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.C.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.C.dim[1]; ++j) {
        internal.C[i - 1 + (j - 1) * shared.dim.C.mult[1]] = (1 - shared.vei[j - 1]) * (I[i - 1 + (j - 1) * shared.dim.I.mult[1]] + A[i - 1 + (j - 1) * shared.dim.A.mult[1]] + S[i - 1 + (j - 1) * shared.dim.S.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.Np.size; ++i) {
      internal.Np[i - 1] = dust2::array::sum<real_type>(internal.N.data(), shared.dim.N, {i - 1, i - 1}, {0, shared.dim.N.dim[1] - 1}) * shared.p[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.n_AU.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_AU.dim[1]; ++j) {
        internal.n_AU[i - 1 + (j - 1) * shared.dim.n_AU.mult[1]] = shared.nu / (1 - shared.ved[j - 1]) * A[i - 1 + (j - 1) * shared.dim.A.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_diag_rec.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_diag_rec.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.n_diag_rec.dim[2]; ++k) {
          internal.n_diag_rec[i - 1 + (j - 1) * shared.dim.n_diag_rec.mult[1] + (k - 1) * shared.dim.n_diag_rec.mult[2]] = shared.diag_rec[i - 1 + (j - 1) * shared.dim.diag_rec.mult[1] + (k - 1) * shared.dim.diag_rec.mult[2]] * internal.n_TU[i - 1 + (k - 1) * shared.dim.n_TU.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wU.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wU.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wU.dim[2]; ++k) {
          internal.wU[i - 1 + (j - 1) * shared.dim.wU.mult[1] + (k - 1) * shared.dim.wU.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * U[i - 1 + (k - 1) * shared.dim.U.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wI.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wI.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wI.dim[2]; ++k) {
          internal.wI[i - 1 + (j - 1) * shared.dim.wI.mult[1] + (k - 1) * shared.dim.wI.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * I[i - 1 + (k - 1) * shared.dim.I.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wA.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wA.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wA.dim[2]; ++k) {
          internal.wA[i - 1 + (j - 1) * shared.dim.wA.mult[1] + (k - 1) * shared.dim.wA.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * A[i - 1 + (k - 1) * shared.dim.A.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wS.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wS.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wS.dim[2]; ++k) {
          internal.wS[i - 1 + (j - 1) * shared.dim.wS.mult[1] + (k - 1) * shared.dim.wS.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * S[i - 1 + (k - 1) * shared.dim.S.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wT.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wT.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wT.dim[2]; ++k) {
          internal.wT[i - 1 + (j - 1) * shared.dim.wT.mult[1] + (k - 1) * shared.dim.wT.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * T[i - 1 + (k - 1) * shared.dim.T.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wdU.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wdU.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wdU.dim[2]; ++k) {
          internal.wdU[i - 1 + (j - 1) * shared.dim.wdU.mult[1] + (k - 1) * shared.dim.wdU.mult[2]] = shared.wd[j - 1 + (k - 1) * shared.dim.wd.mult[1]] * U[i - 1 + (k - 1) * shared.dim.U.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wdI.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wdI.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wdI.dim[2]; ++k) {
          internal.wdI[i - 1 + (j - 1) * shared.dim.wdI.mult[1] + (k - 1) * shared.dim.wdI.mult[2]] = shared.wd[j - 1 + (k - 1) * shared.dim.wd.mult[1]] * I[i - 1 + (k - 1) * shared.dim.I.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wdA.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wdA.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wdA.dim[2]; ++k) {
          internal.wdA[i - 1 + (j - 1) * shared.dim.wdA.mult[1] + (k - 1) * shared.dim.wdA.mult[2]] = shared.wd[j - 1 + (k - 1) * shared.dim.wd.mult[1]] * A[i - 1 + (k - 1) * shared.dim.A.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wdS.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wdS.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wdS.dim[2]; ++k) {
          internal.wdS[i - 1 + (j - 1) * shared.dim.wdS.mult[1] + (k - 1) * shared.dim.wdS.mult[2]] = shared.wd[j - 1 + (k - 1) * shared.dim.wd.mult[1]] * S[i - 1 + (k - 1) * shared.dim.S.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wdT.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wdT.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wdT.dim[2]; ++k) {
          internal.wdT[i - 1 + (j - 1) * shared.dim.wdT.mult[1] + (k - 1) * shared.dim.wdT.mult[2]] = shared.wd[j - 1 + (k - 1) * shared.dim.wd.mult[1]] * T[i - 1 + (k - 1) * shared.dim.T.mult[1]];
        }
      }
    }
    const real_type vax_switch = shared.interpolate_vax_switch.eval(time);
    for (size_t i = 1; i <= shared.dim.prop_C.size; ++i) {
      internal.prop_C[i - 1] = dust2::array::sum<real_type>(internal.C.data(), shared.dim.C, {i - 1, i - 1}, {0, shared.dim.C.dim[1] - 1}) / dust2::array::sum<real_type>(internal.N.data(), shared.dim.N, {i - 1, i - 1}, {0, shared.dim.N.dim[1] - 1});
    }
    for (size_t i = 1; i <= shared.dim.n_ood.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_ood.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.n_ood.dim[2]; ++k) {
          internal.n_ood[i - 1 + (j - 1) * shared.dim.n_ood.mult[1] + (k - 1) * shared.dim.n_ood.mult[2]] = shared.vod[i - 1 + (j - 1) * shared.dim.vod.mult[1] + (k - 1) * shared.dim.vod.mult[2]] * internal.n_TU[i - 1 + (k - 1) * shared.dim.n_TU.mult[1]] * vax_switch;
        }
      }
    }
    const real_type beta = shared.interpolate_beta.eval(time);
    const real_type eta_l = shared.interpolate_eta_l.eval(time);
    const real_type eta_h = shared.interpolate_eta_h.eval(time);
    internal.eta[0] = eta_l;
    internal.eta[1] = eta_h;
    for (size_t i = 1; i <= shared.dim.foi_LH.size; ++i) {
      internal.foi_LH[i - 1] = internal.prop_C[i - 1] * internal.Np[i - 1] / dust2::array::sum<real_type>(internal.Np.data(), shared.dim.Np);
    }
    for (size_t i = 1; i <= shared.dim.n_vod.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_vod.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.n_vod.dim[2]; ++k) {
          internal.n_vod[i - 1 + (j - 1) * shared.dim.n_vod.mult[1] + (k - 1) * shared.dim.n_vod.mult[2]] = internal.n_ood[i - 1 + (j - 1) * shared.dim.n_ood.mult[1] + (k - 1) * shared.dim.n_ood.mult[2]] * shared.u_d[i - 1 + (j - 1) * shared.dim.u_d.mult[1] + (k - 1) * shared.dim.u_d.mult[2]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.lambda.size; ++i) {
      internal.lambda[i - 1] = shared.p[i - 1] * beta * (shared.epsilon * internal.prop_C[i - 1] + (1 - shared.epsilon) * dust2::array::sum<real_type>(internal.foi_LH.data(), shared.dim.foi_LH));
    }
    for (size_t i = 1; i <= shared.dim.n_AT.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_AT.dim[1]; ++j) {
        internal.n_AT[i - 1 + (j - 1) * shared.dim.n_AT.mult[1]] = internal.eta[i - 1] * A[i - 1 + (j - 1) * shared.dim.A.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.screened.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.screened.dim[1]; ++j) {
        internal.screened[i - 1 + (j - 1) * shared.dim.screened.mult[1]] = internal.eta[i - 1] * U[i - 1 + (j - 1) * shared.dim.U.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_UI.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_UI.dim[1]; ++j) {
        internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]] = internal.lambda[i - 1] * (1 - shared.vea[j - 1]) * U[i - 1 + (j - 1) * shared.dim.U.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_oos.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_oos.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.n_oos.dim[2]; ++k) {
          internal.n_oos[i - 1 + (j - 1) * shared.dim.n_oos.mult[1] + (k - 1) * shared.dim.n_oos.mult[2]] = shared.vos[i - 1 + (j - 1) * shared.dim.vos.mult[1] + (k - 1) * shared.dim.vos.mult[2]] * internal.screened[i - 1 + (k - 1) * shared.dim.screened.mult[1]] * vax_switch;
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.n_vos.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_vos.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.n_vos.dim[2]; ++k) {
          internal.n_vos[i - 1 + (j - 1) * shared.dim.n_vos.mult[1] + (k - 1) * shared.dim.n_vos.mult[2]] = internal.n_oos[i - 1 + (j - 1) * shared.dim.n_oos.mult[1] + (k - 1) * shared.dim.n_oos.mult[2]] * shared.u_s[i - 1 + (j - 1) * shared.dim.u_s.mult[1] + (k - 1) * shared.dim.u_s.mult[2]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.U.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.U.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.U.mult[1] + 0] = shared.entrants[i - 1 + (j - 1) * shared.dim.entrants.mult[1]] - internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]] - shared.exr * U[i - 1 + (j - 1) * shared.dim.U.mult[1]] + internal.n_AU[i - 1 + (j - 1) * shared.dim.n_AU.mult[1]] + internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]] - dust2::array::sum<real_type>(internal.n_diag_rec.data(), shared.dim.n_diag_rec, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.n_diag_rec.dim[2] - 1}) + dust2::array::sum<real_type>(internal.wU.data(), shared.dim.wU, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wU.dim[2] - 1}) - dust2::array::sum<real_type>(shared.n_vbe.data(), shared.dim.n_vbe, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.n_vbe.dim[2] - 1}) - dust2::array::sum<real_type>(internal.n_vod.data(), shared.dim.n_vod, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.n_vod.dim[2] - 1}) - dust2::array::sum<real_type>(internal.n_vos.data(), shared.dim.n_vos, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.n_vos.dim[2] - 1}) + dust2::array::sum<real_type>(internal.wdU.data(), shared.dim.wdU, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wdU.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.I.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.I.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.I.mult[1] + shared.odin.offset.state[1]] = internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]] - (shared.sigma + shared.exr) * I[i - 1 + (j - 1) * shared.dim.I.mult[1]] + dust2::array::sum<real_type>(internal.wI.data(), shared.dim.wI, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wI.dim[2] - 1}) + dust2::array::sum<real_type>(internal.wdI.data(), shared.dim.wdI, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wdI.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.A.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.A.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.A.mult[1] + shared.odin.offset.state[2]] = (1 - (1 - shared.ves[j - 1]) * shared.psi) * shared.sigma * I[i - 1 + (j - 1) * shared.dim.I.mult[1]] - internal.n_AT[i - 1 + (j - 1) * shared.dim.n_AT.mult[1]] - internal.n_AU[i - 1 + (j - 1) * shared.dim.n_AU.mult[1]] - shared.exr * A[i - 1 + (j - 1) * shared.dim.A.mult[1]] + dust2::array::sum<real_type>(internal.wA.data(), shared.dim.wA, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wA.dim[2] - 1}) + dust2::array::sum<real_type>(internal.wdA.data(), shared.dim.wdA, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wdA.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.S.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.S.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.S.mult[1] + shared.odin.offset.state[3]] = (1 - shared.ves[j - 1]) * shared.psi * shared.sigma * I[i - 1 + (j - 1) * shared.dim.I.mult[1]] - internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]] - shared.exr * S[i - 1 + (j - 1) * shared.dim.S.mult[1]] + dust2::array::sum<real_type>(internal.wS.data(), shared.dim.wS, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wS.dim[2] - 1}) + dust2::array::sum<real_type>(internal.wdS.data(), shared.dim.wdS, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wdS.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.T.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.T.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.T.mult[1] + shared.odin.offset.state[4]] = internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]] + internal.n_AT[i - 1 + (j - 1) * shared.dim.n_AT.mult[1]] - shared.exr * T[i - 1 + (j - 1) * shared.dim.T.mult[1]] - internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]] + dust2::array::sum<real_type>(internal.wT.data(), shared.dim.wT, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wT.dim[2] - 1}) + dust2::array::sum<real_type>(internal.wdT.data(), shared.dim.wdT, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wdT.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_incid.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_incid.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_incid.mult[1] + shared.odin.offset.state[5]] = internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_diag_a.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_diag_a.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_diag_a.mult[1] + shared.odin.offset.state[6]] = internal.n_AT[i - 1 + (j - 1) * shared.dim.n_AT.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_diag_s.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_diag_s.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_diag_s.mult[1] + shared.odin.offset.state[7]] = internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_treated.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_treated.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_treated.mult[1] + shared.odin.offset.state[8]] = internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_screened.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_screened.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_screened.mult[1] + shared.odin.offset.state[9]] = internal.screened[i - 1 + (j - 1) * shared.dim.screened.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_offered.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_offered.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_offered.mult[1] + shared.odin.offset.state[10]] = internal.n_oos[i - 1 + (j - 1) * shared.dim.n_oos.mult[1] + (j - 1) * shared.dim.n_oos.mult[2]] + internal.n_ood[i - 1 + (j - 1) * shared.dim.n_ood.mult[1] + (j - 1) * shared.dim.n_ood.mult[2]] + shared.n_obe[i - 1 + (j - 1) * shared.dim.n_obe.mult[1] + (j - 1) * shared.dim.n_obe.mult[2]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_vaccinated.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_vaccinated.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_vaccinated.mult[1] + shared.odin.offset.state[11]] = internal.n_vos[i - 1 + (j - 1) * shared.dim.n_vos.mult[1] + (j - 1) * shared.dim.n_vos.mult[2]] + internal.n_vod[i - 1 + (j - 1) * shared.dim.n_vod.mult[1] + (j - 1) * shared.dim.n_vod.mult[2]] + shared.n_vbe[i - 1 + (j - 1) * shared.dim.n_vbe.mult[1] + (j - 1) * shared.dim.n_vbe.mult[2]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_vaccinated_screen.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_vaccinated_screen.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_vaccinated_screen.mult[1] + shared.odin.offset.state[12]] = internal.n_vos[i - 1 + (j - 1) * shared.dim.n_vos.mult[1] + (j - 1) * shared.dim.n_vos.mult[2]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_vbe.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_vbe.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_vbe.mult[1] + shared.odin.offset.state[13]] = shared.n_vbe[i - 1 + (j - 1) * shared.dim.n_vbe.mult[1] + (j - 1) * shared.dim.n_vbe.mult[2]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_offered_vbe.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_offered_vbe.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_offered_vbe.mult[1] + shared.odin.offset.state[14]] = shared.n_obe[i - 1 + (j - 1) * shared.dim.n_obe.mult[1] + (j - 1) * shared.dim.n_obe.mult[2]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_entrants.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_entrants.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_entrants.mult[1] + shared.odin.offset.state[15]] = shared.entrants[i - 1 + (j - 1) * shared.dim.entrants.mult[1]];
      }
    }
  }
  static void output(real_type time, real_type* state, const shared_state& shared, internal_state& internal) {
    const auto * U = state + 0;
    const auto * I = state + shared.odin.offset.state[1];
    const auto * A = state + shared.odin.offset.state[2];
    const auto * S = state + shared.odin.offset.state[3];
    const auto * T = state + shared.odin.offset.state[4];
    const auto * cum_treated = state + shared.odin.offset.state[8];
    const auto * cum_screened = state + shared.odin.offset.state[9];
    const real_type tot_treated = dust2::array::sum<real_type>(cum_treated, shared.dim.cum_treated);
    const real_type tot_attended = dust2::array::sum<real_type>(cum_treated, shared.dim.cum_treated) + dust2::array::sum<real_type>(cum_screened, shared.dim.cum_screened);
    for (size_t i = 1; i <= shared.dim.N.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.N.dim[1]; ++j) {
        internal.N[i - 1 + (j - 1) * shared.dim.N.mult[1]] = U[i - 1 + (j - 1) * shared.dim.U.mult[1]] + I[i - 1 + (j - 1) * shared.dim.I.mult[1]] + A[i - 1 + (j - 1) * shared.dim.A.mult[1]] + S[i - 1 + (j - 1) * shared.dim.S.mult[1]] + T[i - 1 + (j - 1) * shared.dim.T.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.C.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.C.dim[1]; ++j) {
        internal.C[i - 1 + (j - 1) * shared.dim.C.mult[1]] = (1 - shared.vei[j - 1]) * (I[i - 1 + (j - 1) * shared.dim.I.mult[1]] + A[i - 1 + (j - 1) * shared.dim.A.mult[1]] + S[i - 1 + (j - 1) * shared.dim.S.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.Np.size; ++i) {
      internal.Np[i - 1] = dust2::array::sum<real_type>(internal.N.data(), shared.dim.N, {i - 1, i - 1}, {0, shared.dim.N.dim[1] - 1}) * shared.p[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.prop_C.size; ++i) {
      internal.prop_C[i - 1] = dust2::array::sum<real_type>(internal.C.data(), shared.dim.C, {i - 1, i - 1}, {0, shared.dim.C.dim[1] - 1}) / dust2::array::sum<real_type>(internal.N.data(), shared.dim.N, {i - 1, i - 1}, {0, shared.dim.N.dim[1] - 1});
    }
    const real_type beta = shared.interpolate_beta.eval(time);
    const real_type eta_l = shared.interpolate_eta_l.eval(time);
    const real_type eta_h = shared.interpolate_eta_h.eval(time);
    internal.eta[0] = eta_l;
    internal.eta[1] = eta_h;
    for (size_t i = 1; i <= shared.dim.foi_LH.size; ++i) {
      internal.foi_LH[i - 1] = internal.prop_C[i - 1] * internal.Np[i - 1] / dust2::array::sum<real_type>(internal.Np.data(), shared.dim.Np);
    }
    for (size_t i = 1; i <= shared.dim.lambda.size; ++i) {
      internal.lambda[i - 1] = shared.p[i - 1] * beta * (shared.epsilon * internal.prop_C[i - 1] + (1 - shared.epsilon) * dust2::array::sum<real_type>(internal.foi_LH.data(), shared.dim.foi_LH));
    }
    state[shared.odin.offset.state[16]] = tot_treated;
    state[shared.odin.offset.state[17]] = tot_attended;
    state[shared.odin.offset.state[18]] = beta;
    std::copy(internal.eta.begin(), internal.eta.end(), state + shared.odin.offset.state[19]);
    std::copy(internal.N.begin(), internal.N.end(), state + shared.odin.offset.state[20]);
    std::copy(internal.lambda.begin(), internal.lambda.end(), state + shared.odin.offset.state[21]);
  }
  static size_t size_output() {
    return 6;
  }
};
