// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// model.cpp
SEXP dust2_system_model_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _gonovax_dust2_system_model_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// model.cpp
SEXP dust2_system_model_internals(cpp11::sexp ptr, bool include_coefficients, bool include_history);
extern "C" SEXP _gonovax_dust2_system_model_internals(SEXP ptr, SEXP include_coefficients, SEXP include_history) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_internals(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(include_coefficients), cpp11::as_cpp<cpp11::decay_t<bool>>(include_history)));
  END_CPP11
}
// model.cpp
SEXP dust2_system_model_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _gonovax_dust2_system_model_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// model.cpp
SEXP dust2_system_model_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _gonovax_dust2_system_model_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// model.cpp
SEXP dust2_system_model_time(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model.cpp
SEXP dust2_system_model_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model.cpp
SEXP dust2_system_model_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _gonovax_dust2_system_model_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// model.cpp
SEXP dust2_system_model_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _gonovax_dust2_system_model_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// model.cpp
SEXP dust2_system_model_rng_state(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model.cpp
SEXP dust2_system_model_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _gonovax_dust2_system_model_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// model.cpp
SEXP dust2_system_model_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _gonovax_dust2_system_model_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// model.cpp
SEXP dust2_system_model_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _gonovax_dust2_system_model_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// model.cpp
SEXP dust2_system_model_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _gonovax_dust2_system_model_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _gonovax_dust2_system_model_trial_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_internals(cpp11::sexp ptr, bool include_coefficients, bool include_history);
extern "C" SEXP _gonovax_dust2_system_model_trial_internals(SEXP ptr, SEXP include_coefficients, SEXP include_history) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_internals(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(include_coefficients), cpp11::as_cpp<cpp11::decay_t<bool>>(include_history)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _gonovax_dust2_system_model_trial_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _gonovax_dust2_system_model_trial_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_time(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_trial_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_trial_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _gonovax_dust2_system_model_trial_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _gonovax_dust2_system_model_trial_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_rng_state(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_trial_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _gonovax_dust2_system_model_trial_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _gonovax_dust2_system_model_trial_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _gonovax_dust2_system_model_trial_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// model_trial.cpp
SEXP dust2_system_model_trial_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _gonovax_dust2_system_model_trial_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// model_trial_stochastic.cpp
SEXP dust2_system_model_trial_stochastic_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _gonovax_dust2_system_model_trial_stochastic_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_stochastic_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// model_trial_stochastic.cpp
SEXP dust2_system_model_trial_stochastic_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _gonovax_dust2_system_model_trial_stochastic_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_stochastic_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// model_trial_stochastic.cpp
SEXP dust2_system_model_trial_stochastic_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _gonovax_dust2_system_model_trial_stochastic_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_stochastic_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// model_trial_stochastic.cpp
SEXP dust2_system_model_trial_stochastic_time(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_trial_stochastic_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_stochastic_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model_trial_stochastic.cpp
SEXP dust2_system_model_trial_stochastic_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_trial_stochastic_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_stochastic_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model_trial_stochastic.cpp
SEXP dust2_system_model_trial_stochastic_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _gonovax_dust2_system_model_trial_stochastic_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_stochastic_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// model_trial_stochastic.cpp
SEXP dust2_system_model_trial_stochastic_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _gonovax_dust2_system_model_trial_stochastic_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_stochastic_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// model_trial_stochastic.cpp
SEXP dust2_system_model_trial_stochastic_rng_state(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_trial_stochastic_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_stochastic_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model_trial_stochastic.cpp
SEXP dust2_system_model_trial_stochastic_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _gonovax_dust2_system_model_trial_stochastic_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_stochastic_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// model_trial_stochastic.cpp
SEXP dust2_system_model_trial_stochastic_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _gonovax_dust2_system_model_trial_stochastic_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_stochastic_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// model_trial_stochastic.cpp
SEXP dust2_system_model_trial_stochastic_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _gonovax_dust2_system_model_trial_stochastic_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_stochastic_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// model_trial_stochastic.cpp
SEXP dust2_system_model_trial_stochastic_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _gonovax_dust2_system_model_trial_stochastic_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_trial_stochastic_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_internals(cpp11::sexp ptr, bool include_coefficients, bool include_history);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_internals(SEXP ptr, SEXP include_coefficients, SEXP include_history) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_internals(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(include_coefficients), cpp11::as_cpp<cpp11::decay_t<bool>>(include_history)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_time(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_rng_state(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// model_withoutPN.cpp
SEXP dust2_system_model_withoutPN_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _gonovax_dust2_system_model_withoutPN_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withoutPN_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_internals(cpp11::sexp ptr, bool include_coefficients, bool include_history);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_internals(SEXP ptr, SEXP include_coefficients, SEXP include_history) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_internals(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(include_coefficients), cpp11::as_cpp<cpp11::decay_t<bool>>(include_history)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_time(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_rng_state(cpp11::sexp ptr);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// model_withouthistory.cpp
SEXP dust2_system_model_withouthistory_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _gonovax_dust2_system_model_withouthistory_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_model_withouthistory_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_gonovax_dust2_system_model_alloc",                              (DL_FUNC) &_gonovax_dust2_system_model_alloc,                              8},
    {"_gonovax_dust2_system_model_internals",                          (DL_FUNC) &_gonovax_dust2_system_model_internals,                          3},
    {"_gonovax_dust2_system_model_reorder",                            (DL_FUNC) &_gonovax_dust2_system_model_reorder,                            2},
    {"_gonovax_dust2_system_model_rng_state",                          (DL_FUNC) &_gonovax_dust2_system_model_rng_state,                          1},
    {"_gonovax_dust2_system_model_run_to_time",                        (DL_FUNC) &_gonovax_dust2_system_model_run_to_time,                        2},
    {"_gonovax_dust2_system_model_set_rng_state",                      (DL_FUNC) &_gonovax_dust2_system_model_set_rng_state,                      2},
    {"_gonovax_dust2_system_model_set_state",                          (DL_FUNC) &_gonovax_dust2_system_model_set_state,                          2},
    {"_gonovax_dust2_system_model_set_state_initial",                  (DL_FUNC) &_gonovax_dust2_system_model_set_state_initial,                  1},
    {"_gonovax_dust2_system_model_set_time",                           (DL_FUNC) &_gonovax_dust2_system_model_set_time,                           2},
    {"_gonovax_dust2_system_model_simulate",                           (DL_FUNC) &_gonovax_dust2_system_model_simulate,                           5},
    {"_gonovax_dust2_system_model_state",                              (DL_FUNC) &_gonovax_dust2_system_model_state,                              6},
    {"_gonovax_dust2_system_model_time",                               (DL_FUNC) &_gonovax_dust2_system_model_time,                               1},
    {"_gonovax_dust2_system_model_trial_alloc",                        (DL_FUNC) &_gonovax_dust2_system_model_trial_alloc,                        8},
    {"_gonovax_dust2_system_model_trial_internals",                    (DL_FUNC) &_gonovax_dust2_system_model_trial_internals,                    3},
    {"_gonovax_dust2_system_model_trial_reorder",                      (DL_FUNC) &_gonovax_dust2_system_model_trial_reorder,                      2},
    {"_gonovax_dust2_system_model_trial_rng_state",                    (DL_FUNC) &_gonovax_dust2_system_model_trial_rng_state,                    1},
    {"_gonovax_dust2_system_model_trial_run_to_time",                  (DL_FUNC) &_gonovax_dust2_system_model_trial_run_to_time,                  2},
    {"_gonovax_dust2_system_model_trial_set_rng_state",                (DL_FUNC) &_gonovax_dust2_system_model_trial_set_rng_state,                2},
    {"_gonovax_dust2_system_model_trial_set_state",                    (DL_FUNC) &_gonovax_dust2_system_model_trial_set_state,                    2},
    {"_gonovax_dust2_system_model_trial_set_state_initial",            (DL_FUNC) &_gonovax_dust2_system_model_trial_set_state_initial,            1},
    {"_gonovax_dust2_system_model_trial_set_time",                     (DL_FUNC) &_gonovax_dust2_system_model_trial_set_time,                     2},
    {"_gonovax_dust2_system_model_trial_simulate",                     (DL_FUNC) &_gonovax_dust2_system_model_trial_simulate,                     5},
    {"_gonovax_dust2_system_model_trial_state",                        (DL_FUNC) &_gonovax_dust2_system_model_trial_state,                        6},
    {"_gonovax_dust2_system_model_trial_stochastic_alloc",             (DL_FUNC) &_gonovax_dust2_system_model_trial_stochastic_alloc,             8},
    {"_gonovax_dust2_system_model_trial_stochastic_reorder",           (DL_FUNC) &_gonovax_dust2_system_model_trial_stochastic_reorder,           2},
    {"_gonovax_dust2_system_model_trial_stochastic_rng_state",         (DL_FUNC) &_gonovax_dust2_system_model_trial_stochastic_rng_state,         1},
    {"_gonovax_dust2_system_model_trial_stochastic_run_to_time",       (DL_FUNC) &_gonovax_dust2_system_model_trial_stochastic_run_to_time,       2},
    {"_gonovax_dust2_system_model_trial_stochastic_set_rng_state",     (DL_FUNC) &_gonovax_dust2_system_model_trial_stochastic_set_rng_state,     2},
    {"_gonovax_dust2_system_model_trial_stochastic_set_state",         (DL_FUNC) &_gonovax_dust2_system_model_trial_stochastic_set_state,         2},
    {"_gonovax_dust2_system_model_trial_stochastic_set_state_initial", (DL_FUNC) &_gonovax_dust2_system_model_trial_stochastic_set_state_initial, 1},
    {"_gonovax_dust2_system_model_trial_stochastic_set_time",          (DL_FUNC) &_gonovax_dust2_system_model_trial_stochastic_set_time,          2},
    {"_gonovax_dust2_system_model_trial_stochastic_simulate",          (DL_FUNC) &_gonovax_dust2_system_model_trial_stochastic_simulate,          5},
    {"_gonovax_dust2_system_model_trial_stochastic_state",             (DL_FUNC) &_gonovax_dust2_system_model_trial_stochastic_state,             6},
    {"_gonovax_dust2_system_model_trial_stochastic_time",              (DL_FUNC) &_gonovax_dust2_system_model_trial_stochastic_time,              1},
    {"_gonovax_dust2_system_model_trial_stochastic_update_pars",       (DL_FUNC) &_gonovax_dust2_system_model_trial_stochastic_update_pars,       2},
    {"_gonovax_dust2_system_model_trial_time",                         (DL_FUNC) &_gonovax_dust2_system_model_trial_time,                         1},
    {"_gonovax_dust2_system_model_trial_update_pars",                  (DL_FUNC) &_gonovax_dust2_system_model_trial_update_pars,                  2},
    {"_gonovax_dust2_system_model_update_pars",                        (DL_FUNC) &_gonovax_dust2_system_model_update_pars,                        2},
    {"_gonovax_dust2_system_model_withoutPN_alloc",                    (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_alloc,                    8},
    {"_gonovax_dust2_system_model_withoutPN_internals",                (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_internals,                3},
    {"_gonovax_dust2_system_model_withoutPN_reorder",                  (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_reorder,                  2},
    {"_gonovax_dust2_system_model_withoutPN_rng_state",                (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_rng_state,                1},
    {"_gonovax_dust2_system_model_withoutPN_run_to_time",              (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_run_to_time,              2},
    {"_gonovax_dust2_system_model_withoutPN_set_rng_state",            (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_set_rng_state,            2},
    {"_gonovax_dust2_system_model_withoutPN_set_state",                (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_set_state,                2},
    {"_gonovax_dust2_system_model_withoutPN_set_state_initial",        (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_set_state_initial,        1},
    {"_gonovax_dust2_system_model_withoutPN_set_time",                 (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_set_time,                 2},
    {"_gonovax_dust2_system_model_withoutPN_simulate",                 (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_simulate,                 5},
    {"_gonovax_dust2_system_model_withoutPN_state",                    (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_state,                    6},
    {"_gonovax_dust2_system_model_withoutPN_time",                     (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_time,                     1},
    {"_gonovax_dust2_system_model_withoutPN_update_pars",              (DL_FUNC) &_gonovax_dust2_system_model_withoutPN_update_pars,              2},
    {"_gonovax_dust2_system_model_withouthistory_alloc",               (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_alloc,               8},
    {"_gonovax_dust2_system_model_withouthistory_internals",           (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_internals,           3},
    {"_gonovax_dust2_system_model_withouthistory_reorder",             (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_reorder,             2},
    {"_gonovax_dust2_system_model_withouthistory_rng_state",           (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_rng_state,           1},
    {"_gonovax_dust2_system_model_withouthistory_run_to_time",         (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_run_to_time,         2},
    {"_gonovax_dust2_system_model_withouthistory_set_rng_state",       (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_set_rng_state,       2},
    {"_gonovax_dust2_system_model_withouthistory_set_state",           (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_set_state,           2},
    {"_gonovax_dust2_system_model_withouthistory_set_state_initial",   (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_set_state_initial,   1},
    {"_gonovax_dust2_system_model_withouthistory_set_time",            (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_set_time,            2},
    {"_gonovax_dust2_system_model_withouthistory_simulate",            (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_simulate,            5},
    {"_gonovax_dust2_system_model_withouthistory_state",               (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_state,               6},
    {"_gonovax_dust2_system_model_withouthistory_time",                (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_time,                1},
    {"_gonovax_dust2_system_model_withouthistory_update_pars",         (DL_FUNC) &_gonovax_dust2_system_model_withouthistory_update_pars,         2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_gonovax(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
