// Generated by dust2 (version 0.3.22) - do not edit

// Generated by odin2 (version 0.3.21) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(model_trial)]]
// [[dust2::time_type(continuous)]]
// [[dust2::parameter(n_vax, type = "int", rank = 0, required = FALSE, constant = TRUE)]]
// [[dust2::parameter(U0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(I0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(A0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(S0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(T0, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(eta, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(sigma, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(psi, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(nu, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(mu, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(rho, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(lambda, type = "real_type", rank = 0, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(vea, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(ved, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(ves, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(w, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(diag_rec_a, type = "real_type", rank = 3, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(diag_rec_s, type = "real_type", rank = 3, required = TRUE, constant = FALSE)]]
class model_trial {
public:
  model_trial() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 16> state;
      } offset;
    } odin;
    struct dim_type {
      dust2::array::dimensions<2> U;
      dust2::array::dimensions<2> I;
      dust2::array::dimensions<2> A;
      dust2::array::dimensions<2> S;
      dust2::array::dimensions<2> T;
      dust2::array::dimensions<2> U0;
      dust2::array::dimensions<2> I0;
      dust2::array::dimensions<2> A0;
      dust2::array::dimensions<2> S0;
      dust2::array::dimensions<2> T0;
      dust2::array::dimensions<2> N;
      dust2::array::dimensions<2> n_UI;
      dust2::array::dimensions<2> n_AT;
      dust2::array::dimensions<2> n_AU;
      dust2::array::dimensions<2> n_ST;
      dust2::array::dimensions<2> n_TU;
      dust2::array::dimensions<2> screened;
      dust2::array::dimensions<2> pye_trial;
      dust2::array::dimensions<2> pye_noscreen_trial;
      dust2::array::dimensions<3> n_diag_rec;
      dust2::array::dimensions<3> diag_rec_a;
      dust2::array::dimensions<3> diag_rec_s;
      dust2::array::dimensions<2> cum_incid;
      dust2::array::dimensions<2> cum_diag_a;
      dust2::array::dimensions<2> cum_diag_s;
      dust2::array::dimensions<2> cum_treated;
      dust2::array::dimensions<2> cum_screened;
      dust2::array::dimensions<2> cum_pye_trial_pov;
      dust2::array::dimensions<2> cum_pye_noscreen_trial_pov;
      dust2::array::dimensions<2> cum_pye_true;
      dust2::array::dimensions<1> vea;
      dust2::array::dimensions<1> ved;
      dust2::array::dimensions<1> ves;
      dust2::array::dimensions<2> w;
      dust2::array::dimensions<3> wU;
      dust2::array::dimensions<3> wI;
      dust2::array::dimensions<3> wA;
      dust2::array::dimensions<3> wS;
      dust2::array::dimensions<3> wT;
    } dim;
    real_type n_group;
    int n_vax;
    real_type eta;
    real_type sigma;
    real_type psi;
    real_type nu;
    real_type mu;
    real_type rho;
    real_type lambda;
    std::vector<real_type> U0;
    std::vector<real_type> I0;
    std::vector<real_type> A0;
    std::vector<real_type> S0;
    std::vector<real_type> T0;
    std::vector<real_type> vea;
    std::vector<real_type> ved;
    std::vector<real_type> ves;
    std::vector<real_type> w;
    std::vector<real_type> diag_rec_a;
    std::vector<real_type> diag_rec_s;
  };
  struct internal_state {
    std::vector<real_type> n_AT;
    std::vector<real_type> n_ST;
    std::vector<real_type> n_TU;
    std::vector<real_type> screened;
    std::vector<real_type> pye_trial;
    std::vector<real_type> pye_noscreen_trial;
    std::vector<real_type> n_UI;
    std::vector<real_type> n_AU;
    std::vector<real_type> n_diag_rec;
    std::vector<real_type> wU;
    std::vector<real_type> wI;
    std::vector<real_type> wA;
    std::vector<real_type> wS;
    std::vector<real_type> wT;
    std::vector<real_type> N;
  };
  using data_type = dust2::no_data;
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    shared_state::dim_type dim;
    const real_type n_group = 2;
    const int n_vax = dust2::r::read_int(parameters, "n_vax", 1);
    const real_type eta = dust2::r::read_real(parameters, "eta");
    const real_type sigma = dust2::r::read_real(parameters, "sigma");
    const real_type psi = dust2::r::read_real(parameters, "psi");
    const real_type nu = dust2::r::read_real(parameters, "nu");
    const real_type mu = dust2::r::read_real(parameters, "mu");
    const real_type rho = dust2::r::read_real(parameters, "rho");
    const real_type lambda = dust2::r::read_real(parameters, "lambda");
    dim.U.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.I.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.A.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.S.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.T.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.U0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.I0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.A0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.S0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.T0.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.N.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_UI.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_AT.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_AU.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_ST.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_TU.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.screened.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.pye_trial.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.pye_noscreen_trial.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.n_diag_rec.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.diag_rec_a.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.diag_rec_s.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.cum_incid.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_diag_a.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_diag_s.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_treated.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_screened.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_pye_trial_pov.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_pye_noscreen_trial_pov.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.cum_pye_true.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax)});
    dim.vea.set({static_cast<size_t>(n_vax)});
    dim.ved.set({static_cast<size_t>(n_vax)});
    dim.ves.set({static_cast<size_t>(n_vax)});
    dim.w.set({static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wU.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wI.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wA.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wS.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    dim.wT.set({static_cast<size_t>(n_group), static_cast<size_t>(n_vax), static_cast<size_t>(n_vax)});
    std::vector<real_type> U0(dim.U0.size);
    dust2::r::read_real_array(parameters, dim.U0, U0.data(), "U0", true);
    std::vector<real_type> I0(dim.I0.size);
    dust2::r::read_real_array(parameters, dim.I0, I0.data(), "I0", true);
    std::vector<real_type> A0(dim.A0.size);
    dust2::r::read_real_array(parameters, dim.A0, A0.data(), "A0", true);
    std::vector<real_type> S0(dim.S0.size);
    dust2::r::read_real_array(parameters, dim.S0, S0.data(), "S0", true);
    std::vector<real_type> T0(dim.T0.size);
    dust2::r::read_real_array(parameters, dim.T0, T0.data(), "T0", true);
    std::vector<real_type> vea(dim.vea.size);
    dust2::r::read_real_array(parameters, dim.vea, vea.data(), "vea", true);
    std::vector<real_type> ved(dim.ved.size);
    dust2::r::read_real_array(parameters, dim.ved, ved.data(), "ved", true);
    std::vector<real_type> ves(dim.ves.size);
    dust2::r::read_real_array(parameters, dim.ves, ves.data(), "ves", true);
    std::vector<real_type> w(dim.w.size);
    dust2::r::read_real_array(parameters, dim.w, w.data(), "w", true);
    std::vector<real_type> diag_rec_a(dim.diag_rec_a.size);
    dust2::r::read_real_array(parameters, dim.diag_rec_a, diag_rec_a.data(), "diag_rec_a", true);
    std::vector<real_type> diag_rec_s(dim.diag_rec_s.size);
    dust2::r::read_real_array(parameters, dim.diag_rec_s, diag_rec_s.data(), "diag_rec_s", true);
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"U", std::vector<size_t>(dim.U.dim.begin(), dim.U.dim.end())},
      {"I", std::vector<size_t>(dim.I.dim.begin(), dim.I.dim.end())},
      {"A", std::vector<size_t>(dim.A.dim.begin(), dim.A.dim.end())},
      {"S", std::vector<size_t>(dim.S.dim.begin(), dim.S.dim.end())},
      {"T", std::vector<size_t>(dim.T.dim.begin(), dim.T.dim.end())},
      {"cum_incid", std::vector<size_t>(dim.cum_incid.dim.begin(), dim.cum_incid.dim.end())},
      {"cum_diag_a", std::vector<size_t>(dim.cum_diag_a.dim.begin(), dim.cum_diag_a.dim.end())},
      {"cum_diag_s", std::vector<size_t>(dim.cum_diag_s.dim.begin(), dim.cum_diag_s.dim.end())},
      {"cum_treated", std::vector<size_t>(dim.cum_treated.dim.begin(), dim.cum_treated.dim.end())},
      {"cum_screened", std::vector<size_t>(dim.cum_screened.dim.begin(), dim.cum_screened.dim.end())},
      {"cum_pye_trial_pov", std::vector<size_t>(dim.cum_pye_trial_pov.dim.begin(), dim.cum_pye_trial_pov.dim.end())},
      {"cum_pye_noscreen_trial_pov", std::vector<size_t>(dim.cum_pye_noscreen_trial_pov.dim.begin(), dim.cum_pye_noscreen_trial_pov.dim.end())},
      {"cum_pye_true", std::vector<size_t>(dim.cum_pye_true.dim.begin(), dim.cum_pye_true.dim.end())},
      {"tot_treated", {}},
      {"tot_attended", {}},
      {"N", std::vector<size_t>(dim.N.dim.begin(), dim.N.dim.end())}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, dim, n_group, n_vax, eta, sigma, psi, nu, mu, rho, lambda, U0, I0, A0, S0, T0, vea, ved, ves, w, diag_rec_a, diag_rec_s};
  }
  static internal_state build_internal(const shared_state& shared) {
    std::vector<real_type> n_AT(shared.dim.n_AT.size);
    std::vector<real_type> n_ST(shared.dim.n_ST.size);
    std::vector<real_type> n_TU(shared.dim.n_TU.size);
    std::vector<real_type> screened(shared.dim.screened.size);
    std::vector<real_type> pye_trial(shared.dim.pye_trial.size);
    std::vector<real_type> pye_noscreen_trial(shared.dim.pye_noscreen_trial.size);
    std::vector<real_type> n_UI(shared.dim.n_UI.size);
    std::vector<real_type> n_AU(shared.dim.n_AU.size);
    std::vector<real_type> n_diag_rec(shared.dim.n_diag_rec.size);
    std::vector<real_type> wU(shared.dim.wU.size);
    std::vector<real_type> wI(shared.dim.wI.size);
    std::vector<real_type> wA(shared.dim.wA.size);
    std::vector<real_type> wS(shared.dim.wS.size);
    std::vector<real_type> wT(shared.dim.wT.size);
    std::vector<real_type> N(shared.dim.N.size);
    return internal_state{n_AT, n_ST, n_TU, screened, pye_trial, pye_noscreen_trial, n_UI, n_AU, n_diag_rec, wU, wI, wA, wS, wT, N};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.eta = dust2::r::read_real(parameters, "eta", shared.eta);
    shared.sigma = dust2::r::read_real(parameters, "sigma", shared.sigma);
    shared.psi = dust2::r::read_real(parameters, "psi", shared.psi);
    shared.nu = dust2::r::read_real(parameters, "nu", shared.nu);
    shared.mu = dust2::r::read_real(parameters, "mu", shared.mu);
    shared.rho = dust2::r::read_real(parameters, "rho", shared.rho);
    shared.lambda = dust2::r::read_real(parameters, "lambda", shared.lambda);
    dust2::r::read_real_array(parameters, shared.dim.U0, shared.U0.data(), "U0", false);
    dust2::r::read_real_array(parameters, shared.dim.I0, shared.I0.data(), "I0", false);
    dust2::r::read_real_array(parameters, shared.dim.A0, shared.A0.data(), "A0", false);
    dust2::r::read_real_array(parameters, shared.dim.S0, shared.S0.data(), "S0", false);
    dust2::r::read_real_array(parameters, shared.dim.T0, shared.T0.data(), "T0", false);
    dust2::r::read_real_array(parameters, shared.dim.vea, shared.vea.data(), "vea", false);
    dust2::r::read_real_array(parameters, shared.dim.ved, shared.ved.data(), "ved", false);
    dust2::r::read_real_array(parameters, shared.dim.ves, shared.ves.data(), "ves", false);
    dust2::r::read_real_array(parameters, shared.dim.w, shared.w.data(), "w", false);
    dust2::r::read_real_array(parameters, shared.dim.diag_rec_a, shared.diag_rec_a.data(), "diag_rec_a", false);
    dust2::r::read_real_array(parameters, shared.dim.diag_rec_s, shared.diag_rec_s.data(), "diag_rec_s", false);
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    for (size_t i = 1; i <= shared.dim.U.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.U.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.U.mult[1] + 0] = shared.U0[i - 1 + (j - 1) * shared.dim.U0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.I.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.I.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.I.mult[1] + shared.odin.offset.state[1]] = shared.I0[i - 1 + (j - 1) * shared.dim.I0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.A.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.A.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.A.mult[1] + shared.odin.offset.state[2]] = shared.A0[i - 1 + (j - 1) * shared.dim.A0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.S.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.S.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.S.mult[1] + shared.odin.offset.state[3]] = shared.S0[i - 1 + (j - 1) * shared.dim.S0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.T.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.T.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.T.mult[1] + shared.odin.offset.state[4]] = shared.T0[i - 1 + (j - 1) * shared.dim.T0.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_incid.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_incid.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_incid.mult[1] + shared.odin.offset.state[5]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_diag_a.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_diag_a.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_diag_a.mult[1] + shared.odin.offset.state[6]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_diag_s.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_diag_s.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_diag_s.mult[1] + shared.odin.offset.state[7]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_treated.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_treated.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_treated.mult[1] + shared.odin.offset.state[8]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_screened.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_screened.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_screened.mult[1] + shared.odin.offset.state[9]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_pye_trial_pov.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_pye_trial_pov.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_pye_trial_pov.mult[1] + shared.odin.offset.state[10]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_pye_noscreen_trial_pov.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_pye_noscreen_trial_pov.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_pye_noscreen_trial_pov.mult[1] + shared.odin.offset.state[11]] = 0;
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_pye_true.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_pye_true.dim[1]; ++j) {
        state[i - 1 + (j - 1) * shared.dim.cum_pye_true.mult[1] + shared.odin.offset.state[12]] = 0;
      }
    }
  }
  static void rhs(real_type time, const real_type* state, const shared_state& shared, internal_state& internal, real_type* state_deriv) {
    const auto * U = state + 0;
    const auto * I = state + shared.odin.offset.state[1];
    const auto * A = state + shared.odin.offset.state[2];
    const auto * S = state + shared.odin.offset.state[3];
    const auto * T = state + shared.odin.offset.state[4];
    for (size_t i = 1; i <= shared.dim.n_AT.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_AT.dim[1]; ++j) {
        internal.n_AT[i - 1 + (j - 1) * shared.dim.n_AT.mult[1]] = shared.eta * A[i - 1 + (j - 1) * shared.dim.A.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_ST.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_ST.dim[1]; ++j) {
        internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]] = shared.mu * S[i - 1 + (j - 1) * shared.dim.S.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_TU.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_TU.dim[1]; ++j) {
        internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]] = shared.rho * T[i - 1 + (j - 1) * shared.dim.T.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.screened.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.screened.dim[1]; ++j) {
        internal.screened[i - 1 + (j - 1) * shared.dim.screened.mult[1]] = shared.eta * U[i - 1 + (j - 1) * shared.dim.U.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.pye_trial.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.pye_trial.dim[1]; ++j) {
        internal.pye_trial[i - 1 + (j - 1) * shared.dim.pye_trial.mult[1]] = U[i - 1 + (j - 1) * shared.dim.U.mult[1]] + I[i - 1 + (j - 1) * shared.dim.I.mult[1]] + A[i - 1 + (j - 1) * shared.dim.A.mult[1]] + S[i - 1 + (j - 1) * shared.dim.S.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.pye_noscreen_trial.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.pye_noscreen_trial.dim[1]; ++j) {
        internal.pye_noscreen_trial[i - 1 + (j - 1) * shared.dim.pye_noscreen_trial.mult[1]] = U[i - 1 + (j - 1) * shared.dim.U.mult[1]] + I[i - 1 + (j - 1) * shared.dim.I.mult[1]] + A[i - 1 + (j - 1) * shared.dim.A.mult[1]] + S[i - 1 + (j - 1) * shared.dim.S.mult[1]] + T[i - 1 + (j - 1) * shared.dim.T.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_UI.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_UI.dim[1]; ++j) {
        internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]] = shared.lambda * (1 - shared.vea[j - 1]) * U[i - 1 + (j - 1) * shared.dim.U.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.n_AU.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_AU.dim[1]; ++j) {
        internal.n_AU[i - 1 + (j - 1) * shared.dim.n_AU.mult[1]] = (shared.mu == 0 ? shared.nu * A[i - 1 + (j - 1) * shared.dim.A.mult[1]] : shared.nu * shared.mu / (shared.ved[j - 1] * shared.nu + (1 - shared.ved[j - 1]) * shared.mu) * A[i - 1 + (j - 1) * shared.dim.A.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_diag_rec.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.n_diag_rec.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.n_diag_rec.dim[2]; ++k) {
          internal.n_diag_rec[i - 1 + (j - 1) * shared.dim.n_diag_rec.mult[1] + (k - 1) * shared.dim.n_diag_rec.mult[2]] = (shared.diag_rec_s[i - 1 + (j - 1) * shared.dim.diag_rec_s.mult[1] + (k - 1) * shared.dim.diag_rec_s.mult[2]] * internal.n_ST[i - 1 + (k - 1) * shared.dim.n_ST.mult[1]]) + (shared.diag_rec_a[i - 1 + (j - 1) * shared.dim.diag_rec_a.mult[1] + (k - 1) * shared.dim.diag_rec_a.mult[2]] * internal.n_AT[i - 1 + (k - 1) * shared.dim.n_AT.mult[1]]);
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wU.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wU.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wU.dim[2]; ++k) {
          internal.wU[i - 1 + (j - 1) * shared.dim.wU.mult[1] + (k - 1) * shared.dim.wU.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * U[i - 1 + (k - 1) * shared.dim.U.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wI.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wI.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wI.dim[2]; ++k) {
          internal.wI[i - 1 + (j - 1) * shared.dim.wI.mult[1] + (k - 1) * shared.dim.wI.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * I[i - 1 + (k - 1) * shared.dim.I.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wA.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wA.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wA.dim[2]; ++k) {
          internal.wA[i - 1 + (j - 1) * shared.dim.wA.mult[1] + (k - 1) * shared.dim.wA.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * A[i - 1 + (k - 1) * shared.dim.A.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wS.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wS.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wS.dim[2]; ++k) {
          internal.wS[i - 1 + (j - 1) * shared.dim.wS.mult[1] + (k - 1) * shared.dim.wS.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * S[i - 1 + (k - 1) * shared.dim.S.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.wT.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.wT.dim[1]; ++j) {
        for (size_t k = 1; k <= shared.dim.wT.dim[2]; ++k) {
          internal.wT[i - 1 + (j - 1) * shared.dim.wT.mult[1] + (k - 1) * shared.dim.wT.mult[2]] = shared.w[j - 1 + (k - 1) * shared.dim.w.mult[1]] * T[i - 1 + (k - 1) * shared.dim.T.mult[1]];
        }
      }
    }
    for (size_t i = 1; i <= shared.dim.U.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.U.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.U.mult[1] + 0] = -internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]] + internal.n_AU[i - 1 + (j - 1) * shared.dim.n_AU.mult[1]] + internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]] + dust2::array::sum<real_type>(internal.wU.data(), shared.dim.wU, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wU.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.I.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.I.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.I.mult[1] + shared.odin.offset.state[1]] = internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]] - shared.sigma * I[i - 1 + (j - 1) * shared.dim.I.mult[1]] + dust2::array::sum<real_type>(internal.wI.data(), shared.dim.wI, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wI.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.A.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.A.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.A.mult[1] + shared.odin.offset.state[2]] = (1 - (1 - shared.ves[j - 1]) * shared.psi) * shared.sigma * I[i - 1 + (j - 1) * shared.dim.I.mult[1]] - internal.n_AT[i - 1 + (j - 1) * shared.dim.n_AT.mult[1]] - internal.n_AU[i - 1 + (j - 1) * shared.dim.n_AU.mult[1]] + dust2::array::sum<real_type>(internal.wA.data(), shared.dim.wA, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wA.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.S.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.S.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.S.mult[1] + shared.odin.offset.state[3]] = (1 - shared.ves[j - 1]) * shared.psi * shared.sigma * I[i - 1 + (j - 1) * shared.dim.I.mult[1]] - internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]] + dust2::array::sum<real_type>(internal.wS.data(), shared.dim.wS, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wS.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.T.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.T.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.T.mult[1] + shared.odin.offset.state[4]] = internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]] + internal.n_AT[i - 1 + (j - 1) * shared.dim.n_AT.mult[1]] - internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]] + dust2::array::sum<real_type>(internal.wT.data(), shared.dim.wT, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.wT.dim[2] - 1}) - dust2::array::sum<real_type>(internal.n_diag_rec.data(), shared.dim.n_diag_rec, {i - 1, i - 1}, {j - 1, j - 1}, {0, shared.dim.n_diag_rec.dim[2] - 1});
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_incid.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_incid.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_incid.mult[1] + shared.odin.offset.state[5]] = internal.n_UI[i - 1 + (j - 1) * shared.dim.n_UI.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_diag_a.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_diag_a.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_diag_a.mult[1] + shared.odin.offset.state[6]] = internal.n_AT[i - 1 + (j - 1) * shared.dim.n_AT.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_diag_s.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_diag_s.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_diag_s.mult[1] + shared.odin.offset.state[7]] = internal.n_ST[i - 1 + (j - 1) * shared.dim.n_ST.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_treated.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_treated.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_treated.mult[1] + shared.odin.offset.state[8]] = internal.n_TU[i - 1 + (j - 1) * shared.dim.n_TU.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_screened.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_screened.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_screened.mult[1] + shared.odin.offset.state[9]] = internal.screened[i - 1 + (j - 1) * shared.dim.screened.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_pye_trial_pov.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_pye_trial_pov.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_pye_trial_pov.mult[1] + shared.odin.offset.state[10]] = internal.pye_trial[i - 1 + (j - 1) * shared.dim.pye_trial.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_pye_noscreen_trial_pov.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_pye_noscreen_trial_pov.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_pye_noscreen_trial_pov.mult[1] + shared.odin.offset.state[11]] = internal.pye_noscreen_trial[i - 1 + (j - 1) * shared.dim.pye_noscreen_trial.mult[1]];
      }
    }
    for (size_t i = 1; i <= shared.dim.cum_pye_true.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cum_pye_true.dim[1]; ++j) {
        state_deriv[i - 1 + (j - 1) * shared.dim.cum_pye_true.mult[1] + shared.odin.offset.state[12]] = U[i - 1 + (j - 1) * shared.dim.U.mult[1]];
      }
    }
  }
  static void output(real_type time, real_type* state, const shared_state& shared, internal_state& internal) {
    const auto * U = state + 0;
    const auto * I = state + shared.odin.offset.state[1];
    const auto * A = state + shared.odin.offset.state[2];
    const auto * S = state + shared.odin.offset.state[3];
    const auto * T = state + shared.odin.offset.state[4];
    const auto * cum_treated = state + shared.odin.offset.state[8];
    const auto * cum_screened = state + shared.odin.offset.state[9];
    const real_type tot_treated = dust2::array::sum<real_type>(cum_treated, shared.dim.cum_treated);
    const real_type tot_attended = dust2::array::sum<real_type>(cum_treated, shared.dim.cum_treated) + dust2::array::sum<real_type>(cum_screened, shared.dim.cum_screened);
    for (size_t i = 1; i <= shared.dim.N.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.N.dim[1]; ++j) {
        internal.N[i - 1 + (j - 1) * shared.dim.N.mult[1]] = U[i - 1 + (j - 1) * shared.dim.U.mult[1]] + I[i - 1 + (j - 1) * shared.dim.I.mult[1]] + A[i - 1 + (j - 1) * shared.dim.A.mult[1]] + S[i - 1 + (j - 1) * shared.dim.S.mult[1]] + T[i - 1 + (j - 1) * shared.dim.T.mult[1]];
      }
    }
    state[shared.odin.offset.state[13]] = tot_treated;
    state[shared.odin.offset.state[14]] = tot_attended;
    std::copy(internal.N.begin(), internal.N.end(), state + shared.odin.offset.state[15]);
  }
  static size_t size_output() {
    return 3;
  }
};

#include <cpp11.hpp>
#include <dust2/r/continuous/system.hpp>

[[cpp11::register]]
SEXP dust2_system_model_trial_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_continuous_alloc<model_trial>(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads);
}

[[cpp11::register]]
SEXP dust2_system_model_trial_internals(cpp11::sexp ptr, bool include_coefficients, bool include_history) {
  return dust2::r::dust2_system_internals<dust2::dust_continuous<model_trial>>(ptr, include_coefficients, include_history);
}
[[cpp11::register]]
SEXP dust2_system_model_trial_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_run_to_time<dust2::dust_continuous<model_trial>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_model_trial_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_state<dust2::dust_continuous<model_trial>>(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_system_model_trial_time(cpp11::sexp ptr) {
  return dust2::r::dust2_system_time<dust2::dust_continuous<model_trial>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_model_trial_set_state_initial(cpp11::sexp ptr) {
  return dust2::r::dust2_system_set_state_initial<dust2::dust_continuous<model_trial>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_model_trial_set_state(cpp11::sexp ptr, cpp11::list r_state) {
  return dust2::r::dust2_system_set_state<dust2::dust_continuous<model_trial>>(ptr, r_state);
}

[[cpp11::register]]
SEXP dust2_system_model_trial_reorder(cpp11::sexp ptr, cpp11::integers r_index) {
  return dust2::r::dust2_system_reorder<dust2::dust_continuous<model_trial>>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust2_system_model_trial_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_system_rng_state<dust2::dust_continuous<model_trial>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_model_trial_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_system_set_rng_state<dust2::dust_continuous<model_trial>>(ptr, r_rng_state);
}

[[cpp11::register]]
SEXP dust2_system_model_trial_set_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_set_time<dust2::dust_continuous<model_trial>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_model_trial_update_pars(cpp11::sexp ptr, cpp11::list pars) {
  return dust2::r::dust2_system_update_pars<dust2::dust_continuous<model_trial>>(ptr, pars);
}

[[cpp11::register]]
SEXP dust2_system_model_trial_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_simulate<dust2::dust_continuous<model_trial>>(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension);
}
