# Generated by cpp11: do not edit by hand

dust2_system_model_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_gonovax_dust2_system_model_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_model_internals <- function(ptr, include_coefficients, include_history) {
  .Call(`_gonovax_dust2_system_model_internals`, ptr, include_coefficients, include_history)
}

dust2_system_model_run_to_time <- function(ptr, r_time) {
  .Call(`_gonovax_dust2_system_model_run_to_time`, ptr, r_time)
}

dust2_system_model_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_gonovax_dust2_system_model_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_model_time <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_time`, ptr)
}

dust2_system_model_set_state_initial <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_set_state_initial`, ptr)
}

dust2_system_model_set_state <- function(ptr, r_state) {
  .Call(`_gonovax_dust2_system_model_set_state`, ptr, r_state)
}

dust2_system_model_reorder <- function(ptr, r_index) {
  .Call(`_gonovax_dust2_system_model_reorder`, ptr, r_index)
}

dust2_system_model_rng_state <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_rng_state`, ptr)
}

dust2_system_model_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_gonovax_dust2_system_model_set_rng_state`, ptr, r_rng_state)
}

dust2_system_model_set_time <- function(ptr, r_time) {
  .Call(`_gonovax_dust2_system_model_set_time`, ptr, r_time)
}

dust2_system_model_update_pars <- function(ptr, pars) {
  .Call(`_gonovax_dust2_system_model_update_pars`, ptr, pars)
}

dust2_system_model_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_gonovax_dust2_system_model_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_model_trial_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_gonovax_dust2_system_model_trial_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_model_trial_internals <- function(ptr, include_coefficients, include_history) {
  .Call(`_gonovax_dust2_system_model_trial_internals`, ptr, include_coefficients, include_history)
}

dust2_system_model_trial_run_to_time <- function(ptr, r_time) {
  .Call(`_gonovax_dust2_system_model_trial_run_to_time`, ptr, r_time)
}

dust2_system_model_trial_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_gonovax_dust2_system_model_trial_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_model_trial_time <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_trial_time`, ptr)
}

dust2_system_model_trial_set_state_initial <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_trial_set_state_initial`, ptr)
}

dust2_system_model_trial_set_state <- function(ptr, r_state) {
  .Call(`_gonovax_dust2_system_model_trial_set_state`, ptr, r_state)
}

dust2_system_model_trial_reorder <- function(ptr, r_index) {
  .Call(`_gonovax_dust2_system_model_trial_reorder`, ptr, r_index)
}

dust2_system_model_trial_rng_state <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_trial_rng_state`, ptr)
}

dust2_system_model_trial_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_gonovax_dust2_system_model_trial_set_rng_state`, ptr, r_rng_state)
}

dust2_system_model_trial_set_time <- function(ptr, r_time) {
  .Call(`_gonovax_dust2_system_model_trial_set_time`, ptr, r_time)
}

dust2_system_model_trial_update_pars <- function(ptr, pars) {
  .Call(`_gonovax_dust2_system_model_trial_update_pars`, ptr, pars)
}

dust2_system_model_trial_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_gonovax_dust2_system_model_trial_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_model_trial_stochastic_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_gonovax_dust2_system_model_trial_stochastic_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_model_trial_stochastic_run_to_time <- function(ptr, r_time) {
  .Call(`_gonovax_dust2_system_model_trial_stochastic_run_to_time`, ptr, r_time)
}

dust2_system_model_trial_stochastic_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_gonovax_dust2_system_model_trial_stochastic_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_model_trial_stochastic_time <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_trial_stochastic_time`, ptr)
}

dust2_system_model_trial_stochastic_set_state_initial <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_trial_stochastic_set_state_initial`, ptr)
}

dust2_system_model_trial_stochastic_set_state <- function(ptr, r_state) {
  .Call(`_gonovax_dust2_system_model_trial_stochastic_set_state`, ptr, r_state)
}

dust2_system_model_trial_stochastic_reorder <- function(ptr, r_index) {
  .Call(`_gonovax_dust2_system_model_trial_stochastic_reorder`, ptr, r_index)
}

dust2_system_model_trial_stochastic_rng_state <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_trial_stochastic_rng_state`, ptr)
}

dust2_system_model_trial_stochastic_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_gonovax_dust2_system_model_trial_stochastic_set_rng_state`, ptr, r_rng_state)
}

dust2_system_model_trial_stochastic_set_time <- function(ptr, r_time) {
  .Call(`_gonovax_dust2_system_model_trial_stochastic_set_time`, ptr, r_time)
}

dust2_system_model_trial_stochastic_update_pars <- function(ptr, pars) {
  .Call(`_gonovax_dust2_system_model_trial_stochastic_update_pars`, ptr, pars)
}

dust2_system_model_trial_stochastic_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_gonovax_dust2_system_model_trial_stochastic_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_model_withoutPN_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_gonovax_dust2_system_model_withoutPN_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_model_withoutPN_internals <- function(ptr, include_coefficients, include_history) {
  .Call(`_gonovax_dust2_system_model_withoutPN_internals`, ptr, include_coefficients, include_history)
}

dust2_system_model_withoutPN_run_to_time <- function(ptr, r_time) {
  .Call(`_gonovax_dust2_system_model_withoutPN_run_to_time`, ptr, r_time)
}

dust2_system_model_withoutPN_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_gonovax_dust2_system_model_withoutPN_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_model_withoutPN_time <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_withoutPN_time`, ptr)
}

dust2_system_model_withoutPN_set_state_initial <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_withoutPN_set_state_initial`, ptr)
}

dust2_system_model_withoutPN_set_state <- function(ptr, r_state) {
  .Call(`_gonovax_dust2_system_model_withoutPN_set_state`, ptr, r_state)
}

dust2_system_model_withoutPN_reorder <- function(ptr, r_index) {
  .Call(`_gonovax_dust2_system_model_withoutPN_reorder`, ptr, r_index)
}

dust2_system_model_withoutPN_rng_state <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_withoutPN_rng_state`, ptr)
}

dust2_system_model_withoutPN_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_gonovax_dust2_system_model_withoutPN_set_rng_state`, ptr, r_rng_state)
}

dust2_system_model_withoutPN_set_time <- function(ptr, r_time) {
  .Call(`_gonovax_dust2_system_model_withoutPN_set_time`, ptr, r_time)
}

dust2_system_model_withoutPN_update_pars <- function(ptr, pars) {
  .Call(`_gonovax_dust2_system_model_withoutPN_update_pars`, ptr, pars)
}

dust2_system_model_withoutPN_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_gonovax_dust2_system_model_withoutPN_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_model_withouthistory_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_gonovax_dust2_system_model_withouthistory_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_model_withouthistory_internals <- function(ptr, include_coefficients, include_history) {
  .Call(`_gonovax_dust2_system_model_withouthistory_internals`, ptr, include_coefficients, include_history)
}

dust2_system_model_withouthistory_run_to_time <- function(ptr, r_time) {
  .Call(`_gonovax_dust2_system_model_withouthistory_run_to_time`, ptr, r_time)
}

dust2_system_model_withouthistory_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_gonovax_dust2_system_model_withouthistory_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_model_withouthistory_time <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_withouthistory_time`, ptr)
}

dust2_system_model_withouthistory_set_state_initial <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_withouthistory_set_state_initial`, ptr)
}

dust2_system_model_withouthistory_set_state <- function(ptr, r_state) {
  .Call(`_gonovax_dust2_system_model_withouthistory_set_state`, ptr, r_state)
}

dust2_system_model_withouthistory_reorder <- function(ptr, r_index) {
  .Call(`_gonovax_dust2_system_model_withouthistory_reorder`, ptr, r_index)
}

dust2_system_model_withouthistory_rng_state <- function(ptr) {
  .Call(`_gonovax_dust2_system_model_withouthistory_rng_state`, ptr)
}

dust2_system_model_withouthistory_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_gonovax_dust2_system_model_withouthistory_set_rng_state`, ptr, r_rng_state)
}

dust2_system_model_withouthistory_set_time <- function(ptr, r_time) {
  .Call(`_gonovax_dust2_system_model_withouthistory_set_time`, ptr, r_time)
}

dust2_system_model_withouthistory_update_pars <- function(ptr, pars) {
  .Call(`_gonovax_dust2_system_model_withouthistory_update_pars`, ptr, pars)
}

dust2_system_model_withouthistory_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_gonovax_dust2_system_model_withouthistory_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}
