## Generated by dust2 (version 0.3.22) - do not edit
model <- structure(
  function() get("model"),
  class = "dust_system_generator",
  name = "model",
  package = "gonovax",
  path = NULL,
  parameters = data.frame(
    name = c("n_vax", "tt", "U0", "I0", "A0", "S0", "T0", "p", "q", "willing", "enr", "exr", "beta_t", "eta_l_t", "eta_h_t", "epsilon", "sigma", "psi", "nu", "mu", "rho", "kappa", "notifiedprev", "vbe", "vos", "vod", "vopn", "vea", "ved", "ves", "vei", "u_vbe", "u_d", "u_s", "u_pn", "w", "vax_t", "vax_y", "wd", "diag_rec"),
    type = c("int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(0L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 0L, 0L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 3L, 3L, 3L, 3L, 1L, 1L, 1L, 1L, 0L, 3L, 3L, 3L, 2L, 1L, 1L, 2L, 3L)),
  properties = list(
    time_type = "continuous",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = NULL)
model_trial <- structure(
  function() get("model_trial"),
  class = "dust_system_generator",
  name = "model_trial",
  package = "gonovax",
  path = NULL,
  parameters = data.frame(
    name = c("n_vax", "U0", "I0", "A0", "S0", "T0", "eta", "sigma", "psi", "nu", "mu", "rho", "lambda", "vea", "ved", "ves", "w", "diag_rec_a", "diag_rec_s"),
    type = c("int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(0L, 2L, 2L, 2L, 2L, 2L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 2L, 3L, 3L)),
  properties = list(
    time_type = "continuous",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = NULL)
model_trial_stochastic <- structure(
  function() get("model_trial_stochastic"),
  class = "dust_system_generator",
  name = "model_trial_stochastic",
  package = "gonovax",
  path = NULL,
  parameters = data.frame(
    name = c("n_vax", "U0", "I0", "A0", "S0", "T0", "eta", "sigma", "psi", "nu", "mu", "rho", "lambda", "vea", "ved", "ves", "w", "D", "diag_rec_a", "diag_rec_s"),
    type = c("int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(0L, 2L, 2L, 2L, 2L, 2L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 2L, 1L, 3L, 3L)),
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
model_withouthistory <- structure(
  function() get("model_withouthistory"),
  class = "dust_system_generator",
  name = "model_withouthistory",
  package = "gonovax",
  path = NULL,
  parameters = data.frame(
    name = c("n_vax", "tt", "U0", "I0", "A0", "S0", "T0", "p", "q", "willing", "enr", "exr", "beta_t", "eta_l_t", "eta_h_t", "epsilon", "sigma", "psi", "nu", "mu", "rho", "vbe", "vos", "vod", "vea", "ved", "ves", "vei", "u_vbe", "u", "w", "vax_t", "vax_y"),
    type = c("int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(0L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 0L, 0L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 3L, 3L, 3L, 1L, 1L, 1L, 1L, 0L, 3L, 2L, 1L, 1L)),
  properties = list(
    time_type = "continuous",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = NULL)
model_withoutPN <- structure(
  function() get("model_withoutPN"),
  class = "dust_system_generator",
  name = "model_withoutPN",
  package = "gonovax",
  path = NULL,
  parameters = data.frame(
    name = c("n_vax", "tt", "U0", "I0", "A0", "S0", "T0", "p", "q", "willing", "enr", "exr", "beta_t", "eta_l_t", "eta_h_t", "epsilon", "sigma", "psi", "nu", "mu", "rho", "vbe", "vos", "vod", "vea", "ved", "ves", "vei", "u_vbe", "u_d", "u_s", "w", "vax_t", "vax_y", "wd", "diag_rec"),
    type = c("int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(0L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 0L, 0L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 3L, 3L, 3L, 1L, 1L, 1L, 1L, 0L, 3L, 3L, 2L, 1L, 1L, 2L, 3L)),
  properties = list(
    time_type = "continuous",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = NULL)
