## Automatically generated by odin - do not edit
.dualvax <- odin:::odin_c_class("dualvax", list(get_internal = "dualvax_get_internal", finalise = "dualvax_finalise", create = "dualvax_create", initmod_desolve = "dualvax_initmod_desolve", contents = "dualvax_contents", set_user = "dualvax_set_user", metadata = "dualvax_metadata", initial_conditions = "dualvax_initial_conditions", rhs = "dualvax_rhs", rhs_dde = "dualvax_rhs_dde", rhs_desolve = "dualvax_rhs_desolve", output = "dualvax_output_dde", rhs_r = "dualvax_rhs_r"), c("A0", "beta", "eff", "enr", "epsilon", "eta", "exr", "I0", "mu", "nu", "p", "psi", "q", "rho", "S0", "sigma", "T0", "U0", "ve"), list(discrete = FALSE, has_array = TRUE, has_output = TRUE, has_user = TRUE, has_delay = FALSE, has_interpolate = FALSE, has_stochastic = FALSE, has_include = FALSE, initial_time_dependent = FALSE), "gonovax", "odin/dualvax.json", TRUE)
dualvax <- structure(function (A0, beta, eff, enr, epsilon, eta, exr, I0,
    mu, nu, p, psi, q, rho, S0, sigma, T0, U0, ve, user = list(A0 = A0,
        beta = beta, eff = eff, enr = enr, epsilon = epsilon,
        eta = eta, exr = exr, I0 = I0, mu = mu, nu = nu, p = p,
        psi = psi, q = q, rho = rho, S0 = S0, sigma = sigma,
        T0 = T0, U0 = U0, ve = ve), unused_user_action = NULL,
    use_dde = FALSE)
{
    .dualvax$new(user, unused_user_action, use_dde)
}, ir = "odin/dualvax.json", class = "odin_generator")
class(dualvax) <- "odin_generator"
attr(dualvax, "ir") <- .dualvax$public_fields$ir
